\documentclass[12pt]{article}

\usepackage{geometry}               
\geometry{a4paper,
 total={170mm,257mm},
 left=20mm,
 top=20mm,
 bottom=40mm}                   

\setlength{\parindent}{0cm}

%% LOGOS
\usepackage{fancyhdr}
%\setlength{\headheight}{1.5cm}
\addtolength{\headheight}{2cm} % make more space for the header
\pagestyle{fancyplain} % use fancy for all pages except chapter start
\lhead{\includegraphics[height=1.3cm, width=2cm]{../logos/NBIS-logo.png}} % left logo
\rhead{\includegraphics[height=1.3cm, width=4cm]{../logos/SciLifeLab-logo.jpg}} % right logo
\cfoot{}
\renewcommand{\headrulewidth}{0pt} % remove rule below header

%% DEFINE TOOLS AND VARIABLES
\newcommand{\courseName}{ChIP-seq data analysis}
\newcommand{\coursePoints}{1 hp}
\newcommand{\courseLocation}{Stockholm}
\newcommand{\courseDate}{23-24 November 2017}
\newcommand{\courseLastDay}{24 November 2017}
\newcommand{\courseLeaderA}{Olga Dethlefsen}
\newcommand{\courseEmailA}{olga.dethlefsen@nbis.se}
\newcommand{\courseLeaderB}{Agata Smialowska}
\newcommand{\courseEmailB}{agata.smialowska@nbis.se}
\newcommand{\courseExaminer}{Olga Dethlefsen, PhD}
\newcommand{\affilations}{National Bioinformatics Infrastructure Sweden, Science for Life Laboratory, Stockholm University}

<<data, echo=F>>=
student <- st
@

\begin{document}


\large
This is to certify that 


\LARGE
\Sexpr{student}

\large
has successfully taken part in \newline

\LARGE
\begin{center}{\courseName}  \end{center} 


\large
\begin{center} Held in {\courseLocation}, {\courseDate} \end{center} 

\vspace{5mm}
\normalsize
The course consisted of lectures, computer exercises and group discussions. The following subjects and fields were covered in the lectures and exercises:
\begin{itemize}
  \item Quality controls of raw sequencing reads
  \item Reads trimming and filtering
  \item Alignment to the reference genome
  \item Peak-independent quality metrics
  \item Peak calling
  \item Peak-dependent quality metrics and visualization
  \item Differential binding analysis
  \item Common down-stream functional analysis
\end{itemize}


\vspace{5mm}
Examination: Presence during all the lectures and computer/practical exercises

\vspace{5mm}
The course was arranged by the National Bioinformatics Infrastructure Sweden (NBIS) and Science for Life Laboratory (SciLifeLab).

The course is accepted as {\coursePoints} university credits.

\vspace{5mm}
{\courseLocation}, {\courseLastDay}
\vspace{20mm}


{\courseExaminer} \newline
\small
National Bioinformatics Infrastructure Sweden \newline
Science for Life Laboratory \newline
Stockholm University \newline




\end{document}