---
title: "Daily challenge V"
output:
  bookdown::html_document2:
    number_sections: false
  pdf_print: paged
  pdf_document: default
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---


1. What is not correct about likelihood?
    a. likelihood is a generative model
    b. likelihood can be used to estimate how likely it is that a certain model parameter values are true
    c. in linear models, the maximum likelihood estimates are the same least squares estimates
    d. maximum likelihood equates the conditional probability of model parameters given the observed data

2. In Bayesian approach, what is true about the prior and posterior distribution?
    a. prior distribution reflects what we already know about the value of the parameter of interest, the posterior distribution captures our prior knowledge and knowledge coming from observing the data
    b. posterior distribution reflects what we know about the value of the parameter of interest, the prior distribution captures our prior knowledge and knowledge coming from observing the data
    c. prior distribution and posterior distributions are completely unrelated, the prior is used to capture a hypothetical distribution of the model parameter, the posterior captures the knowledge after getting to know the data
    d. none of the above is true

3. For AIC, which of the following statements is *not* true
    a. the relative likelihood, $relL$, can be used to compare models
    b. AIC is a method to address over-fitting
    c. AIC for a model penalizes the maximum logLikelihood with the number of variables in the model
    d. AIC for a model penalizes the maximum likelihood with the number of variables in the model

4. In feature selection, what is *not* true about Lasso?
    a. LASSO stands for least absolute shrinkage and selection operator 
    b. LASSO can be viewed as least squares model parameters estimation that includes a penalty criterion
    c. LASSO can be viewed as a (un-normalized) Bayesian posterior probability
    d. LASSO results in an overfitted model

5. new question needed

6. new question needed

7. new question needed

8. new question needed