---
title: "Precourse quizz"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---



1. What is meant explicitly by the following: 
$\displaystyle \sum_{i=1}^{i=4}(i+1)^{k}$
a) $(i+1)^1 + (i+1)^2 + (i+1)^3 + (i+1)^4$
b) $(1+1)^k + (2+1)^k + (3+1)^k + (4+1)^k$ *
c) $(1+1)^1 + (2+1)^2 + (3+1)^3 + (4+1)^4$
d) none of the above

------

2. What is 
$\displaystyle \sum_{n=2}^{n=4}(100-n^2)$ equal to?
a) 286
b) 71
c) 271 *
d) none of the above

-----

3. We denote mean value as $\bar{x}$ and define it formally as $\displaystyle \bar{x} = \frac{1}{n}\sum_{i=1}^{n}x_i$. Assuming 5 measurements of height (1.62, 1.70, 1.80, 1.65, 1.77) what is the mean value (rounded up to two decimal places)? 


a) 1.7
c) 1.71 *
d) 1.72 
e) none of the above

4. The variance, $\sigma^2$, of a set of observations is defined as "their mean squared distance from the mean value". How would you write it down using the Sigma notation and how much it would be rounded up to three decimal places given the above 5 measurements of height (1.62, 1.70, 1.80, 1.65, 1.77)? 

a) $\displaystyle \sigma^2 = \frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2$, $\sigma^2 = 0.077$ 
b) $\displaystyle \sigma^2 = \frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2$, $\sigma^2 = 0.006$ *
c) $\displaystyle \sigma^2 = \frac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x}^2)$, $\sigma^2 = 0.006$ 
d) none of the above



5. Given matrix 
$$A = \begin{bmatrix} 1 & 3  \\ 2 & 4 \end{bmatrix} $$ and matrix $$B = \begin{bmatrix} 1 & 3  \\ 2 & 4 \end{bmatrix} $$ what is the matrix D, the result of matrix multiplication of A and B (algebraic)?

a) $$D = \begin{bmatrix} 1 & 9  \\ 4 & 16 \end{bmatrix}$$
b) $$D = \begin{bmatrix} 7 & 15  \\ 10 & 22 \end{bmatrix}$$ *
c) $$D = \begin{bmatrix} 10 & 14  \\ 14 & 20 \end{bmatrix}$$
d) none of the above


6. In R, what is the correct command to perform algebraic matrix multiplication of matrix A times matrix B?
a) D = A%*%B
b) D = A*B
c) D = A%*%t(B)
d) D = solve(A)*B

