name: biostat-exer
channels:
  - conda-forge
  - bioconda
dependencies:
  - r=4.1
  - r-markdown=1.1
  - r-rmarkdown=2.15
  - r-ggplot2=3.3.6
  - r-mlbench=2.1-3
  - r-faraway=1.0.7
  - r-ggiraphExtra=0.3.0
  - r-pheatmap=1.0.12
  - r-class=7.3-19
  - r-rpart=4.1-15
  - r-rpart.plot=3.0.9
  - r-randomForest=4.6-14
  - r-lmtest=0.9-40
  - r-glmnet=4.1-2
  - r-readxl=1.4.1
