project:
  type: book
  output-dir: ../docs/SM4LS-book
  pre-render: prerender.R
  post-render: postrender.R
bibliography: references.bib
book:
  title: Statistical Methods for Life Sciences
  chapters:
  - index.qmd
  - part: ../SM4LS-probability/index.qmd
    chapters:
    - ../SM4LS-probability/prob_01intro.qmd
    - ../SM4LS-probability/prob_02discrv.qmd
    - ../SM4LS-probability/prob_exr1_discrv_solutions.qmd
    - ../SM4LS-probability/prob_03contrv.qmd
    - ../SM4LS-probability/prob_04sample.qmd
    - ../SM4LS-probability/prob_exr2_contrv_solutions.qmd
  - part: ../SM4LS-inference/index.qmd
    chapters:
    - ../SM4LS-inference/infe_01hypothesis.qmd
    - ../SM4LS-inference/infe_02hypresamp.qmd
    - ../SM4LS-inference/infe_03hypparm.qmd
    - ../SM4LS-inference/infe_04rank.qmd
    - ../SM4LS-inference/infe_05multiple.qmd
    - ../SM4LS-inference/infe_06interval.qmd
    - ../SM4LS-inference/infe_07anova.qmd
    - ../SM4LS-inference/infe_exr_solutions.qmd
  - part: ../SM4LS-lm/index.qmd
    chapters:
    - ../SM4LS-lm/lm-intro.qmd
    - ../SM4LS-lm/lm-reg-cls.qmd
    - ../SM4LS-lm/lm-coeff.qmd
    - ../SM4LS-lm/lm-intro-exercises.qmd
    - ../SM4LS-lm/lm-diagn-exercises.qmd
    - ../SM4LS-lm/lm-lasso-exercises.qmd
    - ../SM4LS-lm/lm-coeff-exercises.qmd
  - part: ../SM4LS-glm/index.qmd
    chapters:
    - ../SM4LS-glm/glm.qmd
  - part: ../SM4LS-mixedmodels/index.qmd
    chapters:
    - ../SM4LS-mixedmodels/lm.qmd
    - ../SM4LS-mixedmodels/lmm.qmd
    - ../SM4LS-mixedmodels/math.qmd
    - ../SM4LS-mixedmodels/lmm-exr1.qmd
    - ../SM4LS-mixedmodels/lmm-exr2.qmd
  - part: ../SM4LS-survival/index.qmd
    chapters:
    - ../SM4LS-survival/intro.qmd
    - ../SM4LS-survival/regression.qmd
    - ../SM4LS-survival/lab.qmd
  - part: ../SM4LS-pca/index.qmd
    chapters:
    - ../SM4LS-pca/PCA.qmd
    - ../SM4LS-pca/exercises.qmd
  - part: ../SM4LS-clustering/index.qmd
    chapters:
    - ../SM4LS-clustering/intro.qmd
    - ../SM4LS-clustering/exercises.qmd
  - references.qmd
number-sections: true
format:
  html:
    theme: cosmo
    number-sections: true
execute:
  cache: false
  error: false
  warnings: false
