project:
  type: book
  output-dir: ../docs/SM4LS-book
  pre-render: prerender.R
  post-render: postrender.R
bibliography: references.bib
book:
  title: Statistical Methods for Life Sciences
  chapters:
  - index.qmd
  - part: ../SM4LS-probability/index.qmd
    chapters:
    - ../SM4LS-probability/01-why-do-we-care-about-pr.qmd
    - ../SM4LS-probability/02-describing-uncertain-obs.qmd
    - ../SM4LS-probability/03-describing-outcomes-with-pr-models.qmd
    - ../SM4LS-probability/04-repeat-the-sampling.qmd
    - ../SM4LS-probability/05-describing-precision.qmd
    - ../SM4LS-probability/06-exercises.qmd
    - ../SM4LS-probability/prob_02discrv.qmd
    - ../SM4LS-probability/prob_03contrv.qmd
  - part: ../SM4LS-inference/index.qmd
    chapters:
    - ../SM4LS-inference/infe_01hypothesis.qmd
    - ../SM4LS-inference/infe_02hypresamp.qmd
    - ../SM4LS-inference/infe_03hypparm.qmd
    - ../SM4LS-inference/infe_06interval.qmd
    - ../SM4LS-inference/infe_04rank.qmd
    - ../SM4LS-inference/infe_05multiple.qmd
    - ../SM4LS-inference/infe_07anova.qmd
    - ../SM4LS-inference/infe_exr_solutions.qmd
  - part: ../SM4LS-lm/index.qmd
    chapters:
    - ../SM4LS-lm/lm-intro.qmd
    - ../SM4LS-lm/lm-glm.qmd
    - ../SM4LS-lm/lm-coeff.qmd
    - ../SM4LS-lm/lm-intro-exercises.qmd
    - ../SM4LS-lm/lm-diagn-exercises.qmd
    - ../SM4LS-lm/lm-coeff-exercises.qmd
  - part: ../SM4LS-mixedmodels/index.qmd
    chapters:
    - ../SM4LS-mixedmodels/mixmod_lm.qmd
    - ../SM4LS-mixedmodels/mixmod_lmm.qmd
    - ../SM4LS-mixedmodels/mixmod_math.qmd
    - ../SM4LS-mixedmodels/mixmod_exr_solutions.qmd
  - part: ../SM4LS-survival/index.qmd
    chapters:
    - ../SM4LS-survival/intro.qmd
    - ../SM4LS-survival/regression.qmd
    - ../SM4LS-survival/surv_exr_solutions.qmd
  - part: ../SM4LS-pca/index.qmd
    chapters:
    - ../SM4LS-pca/PCA.qmd
    - ../SM4LS-pca/exercises.qmd
  - part: ../SM4LS-clustering/index.qmd
    chapters:
    - ../SM4LS-clustering/intro.qmd
    - ../SM4LS-clustering/exercises.qmd
  - part: ../SM4LS-from-lm-2-ml/index.qmd
    chapters:
    - ../SM4LS-from-lm-2-ml/from-inference-to-prediction.qmd
    - ../SM4LS-from-lm-2-ml/regularization.qmd
    - ../SM4LS-from-lm-2-ml/exr-lasso.qmd
  - references.qmd
number-sections: true
format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: book
    papersize: a4
include-in-header: 
  text: |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
execute:
  cache: false
  error: false
  warnings: false
