project:
  type: book
  output-dir: ../docs/SM4LS-book
  
bibliography: references.bib

book:
  title: "Statistical Methods for Life Sciences"
  author: "Eva Freyhult, Olga Dethlefsen, Payam Emami"
  chapters:
    - index.qmd
    - part: "Probability Theory"
      chapters:
        - ../SM4LS-probability/prob_01intro.qmd
        - ../SM4LS-probability/prob_02discrv.qmd
        - ../SM4LS-probability/prob_exr1_discrv_solutions.qmd 
        - ../SM4LS-probability/prob_03contrv.qmd
        - ../SM4LS-probability/prob_04sample.qmd
        - ../SM4LS-probability/prob_exr2_contrv_solutions.qmd
        - ../SM4LS-probability/references.qmd
    - part: "Inference"
      chapters:
        - ../SM4LS-inference/infe_01hypothesis.qmd
        - ../SM4LS-inference/infe_02hypresamp.qmd
        - ../SM4LS-inference/infe_exr1_hyporesampling_solutions.qmd
        - ../SM4LS-inference/infe_03hypparm.qmd
        - ../SM4LS-inference/infe_04multiple.qmd
        - ../SM4LS-inference/infe_exr2_hypoparam_solutions.qmd
        - ../SM4LS-inference/infe_05interval.qmd
        - ../SM4LS-inference/infe_exr3_interval_solutions.qmd
    - part: "Linear Regression"
      chapters:
        - ../SM4LS-lm/index.qmd
        - ../SM4LS-lm/lm-intro.qmd
        - ../SM4LS-lm/lm-reg-cls.qmd
        - ../SM4LS-lm/lm-coeff.qmd
        - ../SM4LS-lm/lm-intro-exercises.qmd
        - ../SM4LS-lm/lm-diagn-exercises.qmd
        - ../SM4LS-lm/lm-lasso-exercises.qmd
        - ../SM4LS-lm/lm-coeff-exercises.qmd
    - part: "Principal Component Analysis"
      # chapters:
      #   - ../SM4LS-pca/chapters.Rmd
    - part: "Clustering"
      chapters:
        - ../SM4LS-clustering/index.qmd
        - ../SM4LS-clustering/intro.qmd
        - ../SM4LS-clustering/exercises.qmd
    - part: "Generalized Linear Models"
      chapters:
        - ../SM4LS-glm/index.Rmd
        - ../SM4LS-glm/304-linear-GLM.Rmd
    - part: "Mixed Models"
      chapters:
        - ../SM4LS-mixedmodels/index.qmd
        - ../SM4LS-mixedmodels/environment.qmd
        - ../SM4LS-mixedmodels/lm.qmd
        - ../SM4LS-mixedmodels/lmm.qmd
        - ../SM4LS-mixedmodels/math.qmd
    - part: "Survival"
      chapters:
        - ../SM4LS-survival/index.qmd
        - ../SM4LS-survival/intro.qmd
        - ../SM4LS-survival/regression.qmd
        - ../SM4LS-survival/lab.qmd
        - ../SM4LS-survival/references.qmd



number-sections: true

format:
  html:
    theme: cosmo
    fig-width: 3.5
    fig-height: 3.5
    dpi: 600
    number-sections: true

editor: source

execute: 
  cache: true
  echo: false
  error: false
  warnings: false