---
title: "Tuesday morning session"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


## Welcome to Tuesday! 

1. Take a minute to look at [today's questions](https://forms.gle/qYef4p6HwD68D6rJ7) and rate your knowledge
2. Then, in your group discuss:
- yesterday's questions (below); can you agree on the answers?
- anything that you've found confusing or useful yesterday
- and post your answers and comments on our [whiteboard](https://jamboard.google.com/d/15oxwIUbheZfNQMc82B4phuRVr3R4GeOvsxyKrvZ4sR0/edit?usp=sharing)


-----

**Monday's questions**

1. What is meant explicitly by the following: 
$\prod_{n=1}^{3}(n+x)$
a) $(1+x)(2+x)(3+x)$
b) $(0+x)(1+x)(2+x)(3+x)$
c) $(n+1)(n+2)(n03$
d) none of the above

-----

2. What is the results the of the below matrix multiplication? 
$$\begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} \times \begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} $$

a) $$\begin{bmatrix} 1 & 4  \\ 9 & 16 \end{bmatrix}$$
b) $$\begin{bmatrix} 7 & 10  \\ 15 & 22 \end{bmatrix}$$
c) $$\begin{bmatrix} 7 & 15  \\ 10 & 22 \end{bmatrix}$$
d) it is not possible to multiple as the matrix are not rectangular

-----

3. When rolling a six-sided dice, a random variable could be:
a) the number of 6 when rolling dice 100 times
b) the outcome of each individual roll
c) the probability of getting 6
d) the possible outcomes of the roll, that is 1,2,3,4,5 and 6

-----

4. Given Bernoulli, Poisson, Normal and $\chi^2$  distributions what is true?
a) Bernoulli is discrete while Poisson, Normal and $\chi^2$  are continuous
b) Normal and $\chi^2$  are continuous while Bernoulli and Poisson are discrete 
c) Normal is the only one continuous
d) Bernoulli and Poisson are continuous, Normal and $\chi^2$  are discrete

-----

5. Which command is correct to simulate tossing an unbiased coin 10 times?

```{r, eval=F}
a) replicate(5, sample(c("H", "T"), size=2, replace=FALSE))

b) sample(c("H", "T"), size=10, replace=TRUE)

c) sample(c("H", "T", "H", "T", "H", "T", "H", "T","H", "T"), size=1, replace=FALSE)

d) replicate(10, sample(c("H", "T"), size=10, replace=TRUE))
```

-----

6. What is true about probability mass function and density mass function? 

a) probability mass function cam be provided summarized in a table for a continuous random variable
b) probability density function can be provided summarized in a table for a continuous random variable
c) probability mass function cam be provided summarized in table for a discrete random variable
d) probability density function can be provided summarized in a table for a discrete random variable

-----

7. Let $Z \sim N(0,1)$ be a standard normal variable, what is $P(Z < 1.12)$?
a) 0.131
b) 0.869
c) 0.768
d) none of the above

-----

8. Which is true regarding central limit theorem? 
a) everything in nature follows normal distribution
b) the sum of independent and equally distributed random observation is normally distributed if large enough
c) the sum of independent and equally distributed random variables is normally distributed if large enough
d) the sum of random variables is normally distributed if large enough

