---
title: "Test yourself 04"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---

Rate your confidence of being able to answer the below questions saying A, B or C, where:

- A. I am confident that I know the answer to this question
- B. I know at least 50% of the answer to this question, within 20 minutes I could find the required resources to enable a complete answer
- C. I am not confident that I can answer the question at this time.

### Part I

1. PCA
2. PCA
3. PCA

4. Could you explain what clustering is? 

5. Could you explain how k-means works?

6. Could you explain why we are using data splitting into train, validation and test in machine learning?

7. Could you explain how knn classification work using example data and Euclidean distance?

8. Could you explain how a decision tree model is generated (fitted)?

### Part II

1. PCA
2. PCA
3. PCA

4. What is the closest to the definiton of clustering?
a) clustering is about finding the objects similarities expressed in (dis)similarities matrix 
b) clustering is about grouping objects together according to similarity
c) clustering is about finding substructures in a data set
d) none of the above

5. Which is not part of the k-means algorithm
a) selecting $k$ initial centroids
b) randomly assigning each data point to one of $K$ clusters to compute the controids for the initial clusters
c) updating the centroids for each of the $k$ clusters by computing the centroid for all the objects in each of the clusters
d) repeating the above steps until no centroids are left (converegence)

6. What is true about data splitting into train, validation and test in machine learning?
a) we train ML methods such as classification on train data and check models on validation and test data to assess the prediction power on the unknown data sets
b) we use validation data to check if our implementation of ML is working correctly
c) we split data to have multiple dataset to assess ML performance on
d) we split data to deal with overconfident estimation of future performance

7. Given data below and assuming $k=1$ would a new observation (1,2) be classified as A or B?
```{r, echo=F}
x <- c(1, 1, 2, 4, 4, 2)
y <- c(1, 2, 2, 1, 2, 1)
label <- c("A", "A", "A", "B", "B", "?")

data <- data.frame(x = x,  y=y, label = label)
print(data)
```

8. Which of the below are not part of fitting a decision tree?
a) selecting a variable that gives the best split
b) selecting a variable that has a highest variance
c) partitioning the data based on the variable
d) stop splitting when data is split as much as possible  


