title: "Introduction to biostastistics and machine learning"
baseurl: /workshop-mlbiostatistics

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

exclude: ["session-probability/*.Rmd","session-probability/lectures/"]

plugins:
  - jemoji
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url:
  - title: Schedule
    url: schedule
  # - title: Online classroom
  #   url: classroom
  - title: Precourse
    url: precourse
  - title: Travel info
    url: travel
