project:
  type: book
  output-dir: docs

book:
  title: "Introduction to supervised learning"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - KNN-demo.qmd
    - exercises.qmd
    #- references.qmd
    
bibliography: references.bib


format:
  html:
    theme: spacebar
    code-fold: true
    mermaid:
      theme: forest

    
    


