# Preface {.unnumbered}

**Aims**

- to introduce supervised learning for classification and regression

**Learning outcomes**

- to be able to explain supervised learning
- to be able to split data into training, validation and test sets
- to be able to explain basic performance metrics for classification and regression
- to be able to use kknn() function to select the optimal value of $k$ and build KNN classifier 

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared for and used during “Introduction to biostatistics and Machine Learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use the basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*





