\documentclass[12pt]{article}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
\geometry{a4paper, 
 left=30mm,
 top=30mm,
 right=30mm,
 bottom=50mm} 



\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{epstopdf}
\usepackage{float}
\usepackage{hyperref}
\usepackage{amssymb}
\usepackage[backend=bibtex, sorting=none, style=chicago-authordate]{biblatex}
\setlength\bibitemsep{\baselineskip}
\usepackage[british]{babel}
\usepackage[export]{adjustbox}

\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
  linkcolor=blue,% hyperlink text will be green
  urlcolor=blue
}
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}
%\graphicspath{ {/Users/olga/Documents/BILS/!PROJECTS/2616_zebrafish_mut/Documentation/Images/} }

%% LOGOS
\usepackage{fancyhdr}
%\addtolength{\headheight}{2cm} % make more space for the header
%\addtolength{\footheight}{2cm} % make more space for the header

\pagestyle{fancyplain} % use fancy for all pages except chapter start
%\chead{Epigenomics Data Analysis}
%\lhead{\includegraphics[height=1.3cm, width=2cm]{Logos/NBIS-logo.png}} % left logo
%\rhead{\includegraphics[height=1.3cm, width=4cm]{Logos/SciLifeLab-logo.jpg}} % right logo
\renewcommand{\headrulewidth}{0pt} % remove rule below header

\lfoot{\includegraphics[height=2.3cm, width=4cm]{Logos/NBIS-logo.png}} % left logo
\rfoot{\includegraphics[height=2.3cm, width=6cm]{Logos/SciLifeLab-logo.jpg}} % right logo
\cfoot{}

\begin{document}
<<knitr, echo=FALSE>>=
knitr::opts_chunk$set(echo = TRUE,
size="scriptsize", 
warning = FALSE, 
message = FALSE,
error = TRUE, 
fig.path = "Epi-flyer-figures/",
cache=FALSE)#, 
#cache.path = "../../scratch/cache/3696-report/"
#)
@

% FRONT PAGE

% Course title
\Huge
\textbf{Introduction to biostatistics and machine learning} % course title
\normalsize
Short course

% Date 
\LARGE
\vspace{1.5cm}
\begin{flushright} \textbf{May, 11th - 15th, 2020} % date

% Location
\normalsize
SciLifeLab, Uppsala University, BMC, Husargatan 3 % location

% Generic NBIS course description
\vspace{0.5cm}
National course open for PhD students, postdocs, researchers and other employees within Swedish universities.  

% Link to website annoucement & NBIS website
\normalsize
\vspace{0.5cm}
\href{https://nbisweden.github.io/workshop-mlbiostatistics/}{https://nbisweden.github.io/workshop-mlbiostatistics/}

\end{flushright} 

% Insert QR-code
\begin{figure}[H]
\includegraphics[width=3cm, height=3cm, right]{QR-code.png}
\end{figure}



% Course specific text
\vspace{0.1cm}
\Large
%\begin{flushleft}
\centering{
Short introduction to R with R-Studio. Probability theory. Hypothesis testing and confidence intervals. Resampling. Linear and logistic regression methods. Model selection. Unsupervised learning incl. clustering and dimension reduction methods. Supervised learning incl. classification. Primer on decision trees and Artificial Neural Networks
}

\large
\vspace{0.2cm}
\centering{with focus on Active Learning Approach}
%\end{flushleft}

% % BACK-PAGE
% \newpage 
% \cfoot{}
% % NBIS training events
% \Large
% \begin{flushleft}
% \textbf{NBIS training events}
% \newline \normalsize
% Up-coming events
% \end{flushleft}
% \vspace{0.5cm}
% \begin{flushleft}
% 
% 
%   \footnotesize \textbf{RNA-seq data analysis} \newline \scriptsize
%   starts May, 13th, Uppsala
%   
%   \footnotesize \textbf{Intro. to Bioinformatics using NGS data} \newline \scriptsize
%   starts May, 20th, G\"oteborg
%   
%   \footnotesize \textbf{Biostatistics Essentials} \newline \scriptsize
%   starts May, 21st, Uppsala
%   
%   \footnotesize \textbf{Data integration} \newline \scriptsize
%   starts September, 9th, Stockholm
%   
%   \footnotesize \textbf{Bioinformatics for Principal Investigators} \newline \scriptsize
%   starts September, 17th, Stockholm
%   
%   \footnotesize \textbf{Python programming} \newline \scriptsize
%   starts September, 23th, Uppsala
%   
%   
% \vspace{1cm}
% More events \& information: \newline
% \href{https://nbis.se/training/events.html}{https://nbis.se/training/events.html}
% 
% \end{flushleft}





\end{document}  

