channels:
  - conda-forge
  - bioconda
dependencies:
  # R env
  - r=4.1
  - r-renv=0.15.4
  - r-tidyverse=1.3.1     # `renv` takes much longer time
  - r-janitor=2.1.0        # Rmarkdown
  - r-kableextra=1.3.4     # Rmarkdown
  - r-proj4=1.0_11    # error during installation of 'ggalt' package

