project:
  type: book
  output-dir: docs
  
book:
  title: "Statistical Inference"
  author: "Eva Freyhult"
  chapters:
    - index.qmd
    - infe_01hypothesis.qmd
    - infe_exr1_hyporesampling_solutions.qmd
    - infe_02hypparm.qmd
    - infe_03multiple.qmd
    - infe_exr2_hypoparam_solutions.qmd
    - infe_04interval.qmd
    - infe_exr3_interval_solutions.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
  pdf:
    documentclass: scrreprt

editor: source

execute: 
  echo: false
