---
title: "Exercises: Hypothesis tests, parametric"
date: "2022-09-13"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
require(tidyverse)
require(kableExtra)
```


```{exercise, label="Hb1", echo=TRUE}
The hemoglobin value (Hb) in women is  on average 140 g/L. You observe the following Hb values in a set of five male blood donors: 154, 140, 147, 162, 172. Assume that Hb is normally distributed. Is there a reason to believe that the mean Hb value in men differ from that in women? 
```


```{exercise, label="Hb2", echo=TRUE}
The hemoglobin value (Hb) in men is on average 188 g/L. The Hb values in \@ref(exr:Hb1) were actually measured after the men had donated blood. Is there a reason to believe that the mean Hb level for men after blood donation is less than 188 g/L?
```


```{exercise, label="Hb3", echo=TRUE}
By observing the Hb values in 5 male blood donors; 154, 140, 147, 162, 172 g/L, and 5 female blood donors: 123, 140, 137, 132, 127 g/L, is there a reason to believe that the Hb level is higher in men than in women?
```


```{exercise, label="Hb4", echo=TRUE}
Based on statistics from blodcentralen we learn that male Hb values (before donation) is normally distributed with mean 188 g/L and standard deviation 16 g/L. Using this new information and the following observed Hb values in five male donors after donation; 154, 140, 147, 162, 172 g/L, is there reason to belive that the mean Hb value for men after blood donation is lower than 188 g/L?
```


```{exercise, label="mice12", echo=TRUE}
In order to study the effect of high-fat diet 12 mice are fed normal diet (control group) and 12 mice are fed high-fat diet. After a couple of weeks the mouse weights in gram are recorded;
```

```{r miceobs, echo=FALSE}
## 12 HF mice
xHF <- c(25, 30, 23, 18, 31, 24, 39, 26, 36, 29, 23, 32)
## 12 control mice
xN <- c(27, 25, 22, 23, 25, 37, 24, 26, 21, 26, 30, 24)

kable(rbind("high-fat"=xHF, "ordinary"=xN), digits=1) %>% kable_styling(font_size=14)
```

Does high fat diet increase body weight in mice?
  
a) Assume equal variances.
b) Don't assume equal variances.



<!-- Exercise, known $\sigma$ -->
<!-- If the means of the populations are unknown, but the standard variations are known -->
<!-- Let's assume that both mouse body weights in control and treatment groups are independent and normally distributed, with unknown mean, but known standard deviations, $\sigma_1=3.4$ and $\sigma_2=5.1$. -->
  
  <!-- ```{r echo=F, eval=FALSE} -->
  <!-- ## Our observed value -->
  <!-- dobs -->
  <!-- ## The p-value -->
  <!-- 1-pnorm(dobs, mean=0, sd=sqrt(5.1^2/12 + 3.4^2/12)) -->
  <!-- 1-pnorm((dobs-0)/sqrt(5.1^2/12 + 3.4^2/12)) -->
  <!-- pnorm(dobs, mean=0, sd=sqrt(5.1^2/12 + 3.4^2/12), lower.tail=FALSE) -->
  <!-- pnorm((dobs-0)/sqrt(5.1^2/12 + 3.4^2/12), lower.tail=FALSE) -->
  <!-- ``` -->
  


