project:
  type: book
  output-dir: docs

book:
  title: "Introduction to linear models"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - lm-intro.qmd
    - lm-ml.qmd
    #- lm-intro-exercises.qmd
    #- lm-glm.qm
    #- lm-coeff.qmd
    # - lm-coeff-exercises.qmd
    # - lm-diagn-exercises.qmd
    # - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  # pdf:
  #   documentclass: scrreprt



