# Preface {.unnumbered}

Linear models allows us to answer questions such as: 

- is there a relationship between exposure and outcome, e.g. height and weight?
- how strong is the relationship between the two variables?
- what will be a predicted value of the outcome given a new set of exposure values?
- how accurately can we predict outcome?
- which variables are associated with the response, e.g. is it only height that explains weight or could it be height and age that are both associated with the response?
  

**Learning outcomes**

- to understand what a linear model is and be familiar with the terminology
- to be able to state linear model in the general vector-matrix notation
- to be able to use the general vector-matrix notation to numerically estimate model parameters
- to be able to use `lm()` function for model fitting, parameter estimation, hypothesis testing and prediction
- to be able to evaluate model fit by interpreting $R^2$ and $R^2(adj)$ values
- to be able to check model assumptions
- to be able to use `glm()` for extending linear models into generalized linear models

Do you see a mistake or a typo? I would be grateful if you let me know via [olga.dethlefsen@nbis.se](olga.dethlefsen@nbis.se)

*This repository contains teaching and learning materials prepared and used during "Introduction to biostatistics and machine learning" course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)*

