{
  "hash": "ccc2c2ab3eda51ede7f4a7fe69e65fc1",
  "result": {
    "engine": "knitr",
    "markdown": "# Exercises (regression coefficients) {.unnumbered}\n\n\n\n\n:::{#exr-lm}\n\n## Dose, genotype and enzyme activity\n\nAn experiment investigates how the activity of an enzyme changes with drug dose. Measurements were obtained from two genotypes, `WT` and `Mutant`, and samples were processed in three experimental batches.\n\nCopy and run the code below to create the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenotype <- factor(\n  rep(c(\"WT\", \"Mutant\"), each = 24),\n  levels = c(\"WT\", \"Mutant\")\n)\n\ndose <- rep(\n  rep(c(0, 2, 4, 6, 8, 10), each = 4),\n  2\n)\n\nbatch <- factor(\n  rep(c(\"B1\", \"B2\", \"B3\"), length.out = 48),\n  levels = c(\"B1\", \"B2\", \"B3\")\n)\n\nactivity <- c(\n  13.43, 13.44, 10.60, 10.36,\n  12.34, 13.12, 12.75, 13.67,\n  14.61, 15.53, 13.64, 16.10,\n  14.77, 20.82, 17.47, 16.79,\n  21.95, 18.53, 20.10, 20.34,\n  21.73, 22.38, 20.82, 19.50,\n  14.65, 14.93, 10.53, 16.83,\n  15.47, 13.89, 15.64, 19.03,\n  22.03, 20.09, 20.89, 19.93,\n  23.02, 24.61, 21.32, 24.07,\n  28.11, 22.73, 26.46, 27.81,\n  29.73, 28.64, 28.97, 27.76\n)\n\nenzyme <- data.frame(\n  activity,\n  dose,\n  genotype,\n  batch\n)\n\nhead(enzyme)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  activity dose genotype batch\n1    13.43    0       WT    B1\n2    13.44    0       WT    B2\n3    10.60    0       WT    B3\n4    10.36    0       WT    B1\n5    12.34    2       WT    B2\n6    13.12    2       WT    B3\n```\n\n\n:::\n:::\n\n\n\na) Make an exploratory plot of `activity` against `dose`, using different\ncolours for the two genotypes. What patterns do you see?\n\nb) Fit a linear model in R to model enzyme activity given `dose`, `genotype`\nand `batch`.\n\nc) What are the reference categories for `genotype` and `batch`?\n\nd) Given the fitted model, what is the expected enzyme activity for a\n`Mutant` sample with a `dose` of 5 from batch `B2`? Calculate using the model and check your calculations using `predict()` function.\n\ne) Which model coefficients show evidence of an association with enzyme\nactivity at the 5% significance level?\n\n:::\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\n\na)\n\n\n::: {.cell warnings='false' messages='false'}\n\n```{.r .cell-code  code-fold=\"false\"}\nggplot(enzyme, aes(x = dose, y = activity, colour = genotype)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-coeff-exercises_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nEnzyme activity appears to increase with increasing dose. The Mutant\nsamples also tend to have higher enzyme activity than the WT samples.\n\nb) \n\n\n::: {.cell warnings='false' messages='false'}\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel1 <- lm(\n  activity ~ dose + genotype + batch,\n  data = enzyme\n)\n\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = activity ~ dose + genotype + batch, data = enzyme)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.7464 -0.8783  0.1982  1.0280  3.2338 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    10.19616    0.61019  16.710  < 2e-16 ***\ndose            1.27206    0.07497  16.968  < 2e-16 ***\ngenotypeMutant  5.09792    0.50846  10.026 7.97e-13 ***\nbatchB2         0.69710    0.62386   1.117    0.270    \nbatchB3        -1.01768    0.62722  -1.623    0.112    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.761 on 43 degrees of freedom\nMultiple R-squared:  0.9015,\tAdjusted R-squared:  0.8924 \nF-statistic:  98.4 on 4 and 43 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nc) \n\nThe reference categories are: WT for genotype and B1 for batch.\n\nThe coefficients for genotypeMutant, batchB2 and batchB3 therefore\ndescribe differences relative to these reference categories.\n\nd) \n\nFrom the fitted model,\n\n$$ \\widehat{activity} = 10.196 + 1.272 \\cdot dose + 5.098 \\cdot I_{\\text{Mutant}} + 0.697 \\cdot I_{\\text{B2}} - 1.018 \\cdot I_{\\text{B3}}. $$\n\nFor a Mutant sample with dose = 5 from batch B2:\n\n$$ \\widehat{activity} = 10.196 + 1.272 \\cdot 5 + 5.098 + 0.697 \\approx 22.35. $$\n\nWe can also obtain the prediction in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_sample <- data.frame(\n  dose = 5,\n  genotype = factor(\"Mutant\", levels = levels(enzyme$genotype)),\n  batch = factor(\"B2\", levels = levels(enzyme$batch))\n)\n\npredict(model1, newdata = new_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n22.35146 \n```\n\n\n:::\n:::\n\n\ne) \n\nAt the 5% significance level:\n\n- dose shows evidence of an association with enzyme activity ($p < 2\\times10^{-16}$);\n- genotypeMutant shows evidence of an association with enzyme activity ($p = 7.97\\times10^{-13}$);\n- there is no evidence that batchB2 differs from the reference batch B1 ($p = 0.270$);\n- there is no evidence that batchB3 differs from the reference batch B1 ($p = 0.112$).\n\nThus, dose and genotype are clearly associated with enzyme activity in\nthis fitted model, while the individual batch coefficients are not\nsignificantly different from the reference batch.\n\n:::\n\n\n::: {#exr-logistic}\n\n## Treatment response\n\nA clinical study investigates whether a biomarker and treatment are associated\nwith the probability of responding to treatment.\n\nThe outcome `response` is coded as:\n\n- `1`: responded to treatment\n- `0`: did not respond\n\nThe data also contain:\n\n- `marker`: a continuous biomarker measurement\n- `treatment`: either `Control` or `Drug`\n- `age`: age in years\n\nCopy and run the code below to create the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(\n  0,1,0,0,1,1,1,1,0,1,\n  0,0,0,1,1,1,1,1,0,1,\n  0,0,0,1,0,1,1,1,0,1,\n  0,0,0,1,0,1,1,1,1,1,\n  1,1,1,1,0,1,0,1,0,1,\n  0,0,0,0,0,1,1,1,0,1\n)\n\nmarker <- rep(\n  c(0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 1.2, 2.8),\n  6\n)\n\ntreatment <- factor(\n  rep(c(\"Control\", \"Drug\"), 30),\n  levels = c(\"Control\", \"Drug\")\n)\n\nage <- rep(\n  c(35, 42, 51, 60, 67, 48, 55, 39, 63, 45),\n  6\n)\n\ntrial <- data.frame(\n  response,\n  marker,\n  treatment,\n  age\n)\n\nhead(trial)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  response marker treatment age\n1        0    0.5   Control  35\n2        1    1.0      Drug  42\n3        0    1.5   Control  51\n4        0    2.0      Drug  60\n5        1    2.5   Control  67\n6        1    3.0      Drug  48\n```\n\n\n:::\n:::\n\n\n\na) Fit a logistic regression model to model the probability of `response`\ngiven `marker`, `treatment` and `age`.\n\nb) What is the reference category for `treatment`? What comparison does the\ncoefficient `treatmentDrug` therefore represent?\n\nc) Using the Wald tests reported in the model summary, which coefficients show\nevidence of an association with the probability of response at the 5%\nsignificance level?\n\nd) The estimated coefficient for `marker` is approximately $1.75$.\n\n- Calculate the corresponding odds ratio.\n- Interpret this odds ratio in the context of the study.\n\ne) The estimated coefficient for `treatmentDrug` is approximately $1.51$.\n\n- Calculate the corresponding odds ratio.\n- Interpret this odds ratio in the context of the study.\n\nf) Using the fitted model, estimate the probability of response for a\n50-year-old patient with a `marker` value of 2.5 who receives the `Drug`\ntreatment. Check your answer using `predict()` with `type = \"response\"`.\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\n\na) \n\nFit the logistic regression model:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel2 <- glm(\n  response ~ marker + treatment + age,\n  family = binomial(link = \"logit\"),\n  data = trial\n)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = response ~ marker + treatment + age, family = binomial(link = \"logit\"), \n    data = trial)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -0.96994    2.18446  -0.444 0.657031    \nmarker         1.75274    0.51477   3.405 0.000662 ***\ntreatmentDrug  1.50666    0.76777   1.962 0.049717 *  \nage           -0.05776    0.04477  -1.290 0.197067    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 82.108  on 59  degrees of freedom\nResidual deviance: 47.317  on 56  degrees of freedom\nAIC: 55.317\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nb) \n\nThe reference category for treatment is Control.\n\nTherefore, the coefficient treatmentDrug compares patients receiving the\nDrug treatment with patients receiving the Control treatment, while\nmarker and age are held constant.\n\nc) \n\nAt the 5% significance level:\n\n- marker shows evidence of an association with the probability of response ($p = 0.000662$);\n- treatmentDrug shows evidence of an association with the probability of response ($p = 0.0497$);\n- age does not show evidence of an association with the probability of response ($p = 0.197$).\n\nd) \nThe estimated coefficient for marker is\n\n$$ \\hat{\\beta}_{marker} = 1.753. $$\n\nThe corresponding odds ratio is\n\n$$ \\exp(1.753) \\approx 5.77. $$\n\nThus, for a one-unit increase in marker, the odds of treatment response are\nestimated to be approximately 5.8 times higher, with treatment and age held\nconstant.\n\ne) The estimated coefficient for treatmentDrug is\n\n$$ \\hat{\\beta}_{Drug} = 1.507. $$\n\nThe corresponding odds ratio is\n\n$$ \\exp(1.507) \\approx 4.51. $$\n\nThus, patients receiving the Drug have approximately 4.5 times the odds of\nresponse compared with patients receiving Control, with marker and age\nheld constant.\n\nThe odds ratios can also be calculated in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|code-fold: false\nexp(coef(model2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)        marker treatmentDrug           age \n    0.3791070     5.7703864     4.5116284     0.9438804 \n```\n\n\n:::\n:::\n\n\n\nf) \n\nFor a 50-year-old patient with marker = 2.5 receiving the Drug, the fitted\nlog-odds are\n\n$$ -0.970 + 1.753(2.5) + 1.507 - 0.058(50) \\approx 2.03. $$\n\nConverting the log-odds to a probability gives\n\n$$ p = \\frac{\\exp(2.03)} {1+\\exp(2.03)} \\approx 0.884. $$\n\nThus, the fitted model predicts a probability of response of approximately\n88%.\n\nWe can check this directly in R:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nnew_patient <- data.frame(\n  marker = 2.5,\n  treatment = factor(\n    \"Drug\",\n    levels = levels(trial$treatment)\n  ),\n  age = 50\n)\n\npredict(\n  model2,\n  newdata = new_patient,\n  type = \"response\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1 \n0.8839909 \n```\n\n\n:::\n:::\n\n\n\n\n:::",
    "supporting": [
      "lm-coeff-exercises_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}