---
title: "Wrap-up"
# author: Olga Dethlefsen
format: 
  revealjs:
    slide-number: true
    theme: [default, custom.scss]
    view-distance: 10
    chalkboard: 
      buttons: true
  html:
    code-fold: false
editor_options: 
  chunk_output_type: console
bibliography: references.bib
---

## Group discussion

You are a part of research team conducting a lung cancer study. You have collected measurements for 2000 genes for 50 healthy and 50 cancer patients. You also know from previous study that this type of cancer is more likely to occur in older people and in people who smoke, so in addition to gene expression measurements you note down subjects age and smoking status (Yes/No).

Your supervisor knows you are fresh back from the "Introduction to Biostatistics & ML" course and asks you to be in charge of writing a **data analysis** plan to be presented at the next group meeting. How can the methods discussed during the course be used to further understand molecular mechanisms of lung cancer? What analyses will you suggest?

- If you are in [1] use methods from day 1
- If you are in [2] use methods from day 2
- If you are in [3] use methods from day 3
- If you are in [4+5] use methods from day 4
- If you are in [6] use methods from day 5

## Materials availability
<br>

https://uppsala.instructure.com/courses/70535

## Recommended books {.smaller}
<br>

### Biostatistics

- Medical Statistics at a Glance by Aviva Petrie and Caroline Sabin
- Essential Medical Statistics by Kirkwood and Sterne
- Practical Statistics for Data Scientists: 50 Essential Concepts by Peter Bruce and Andrew Bruce

### Linear models 

- Linear Models with R by Julian J. Faraway (second edition)
- Extending the Linear Models with R by Julian J. Faraway (second edition)
- Data Analysis Using Regression and Multilevel/Hierarchical Models by Andrew Gelman & Jennifer Hill

### Statistics & machine learning 

- An Introduction to Statistical Learning with Application in R by Gareth James, Daniela Witten, Trevor Hastie & Robert Tibshirani (second edition) (free download Links to an external site.) 
- Data Analysis for the Life Sciences with R by Rafael A. Irizarry, Michael I. Love (free download Links to an external site.)
- Hands-on Machine Learning with Scikit-Learn, Keras & TensorFlow by Aurelien Geron
- Elements of Statistical Learning: data mining, inference and prediction by Trevor Hastie, Robert Tibshirani & Jerome Friedman

## Contact

- edu.ml-biostats@nbis.se
- olga.dethlefsen@nbis.se
- eva.freyhult@nbis.se
- payam.emami@nbis.se
- mungwan.hong@nbis.se
- julie.lorent@nbis.se

## Follow-up session

- any interest?

## Drop-in

https://nbis.se/support/dropin.html
 

## Training events

https://nbis.se/training/events.html
https://www.scilifelab.se/events/#calendar


## Feedback

## Well done & massive thank you! 



