<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Survival Analysis - 2&nbsp; Regression with survival response</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lab.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with survival response</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survival Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with survival response</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R examples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#cox-proportional-hazards-model" id="toc-cox-proportional-hazards-model" class="nav-link active" data-scroll-target="#cox-proportional-hazards-model"><span class="header-section-number">2.1</span> Cox proportional hazards model</a></li>
  <li><a href="#example-with-brain-cancer-data" id="toc-example-with-brain-cancer-data" class="nav-link" data-scroll-target="#example-with-brain-cancer-data"><span class="header-section-number">2.2</span> Example with brain cancer data</a>
  <ul class="collapse">
  <li><a href="#coefficient-interpration" id="toc-coefficient-interpration" class="nav-link" data-scroll-target="#coefficient-interpration"><span class="header-section-number">2.2.1</span> Coefficient interpration</a></li>
  <li><a href="#global-statistical-signficance" id="toc-global-statistical-signficance" class="nav-link" data-scroll-target="#global-statistical-signficance"><span class="header-section-number">2.2.2</span> Global statistical signficance</a></li>
  <li><a href="#concordance" id="toc-concordance" class="nav-link" data-scroll-target="#concordance"><span class="header-section-number">2.2.3</span> Concordance</a></li>
  <li><a href="#predictions" id="toc-predictions" class="nav-link" data-scroll-target="#predictions"><span class="header-section-number">2.2.4</span> Predictions</a></li>
  </ul></li>
  <li><a href="#time-dependent-covariates" id="toc-time-dependent-covariates" class="nav-link" data-scroll-target="#time-dependent-covariates"><span class="header-section-number">2.3</span> Time-dependent covariates</a></li>
  <li><a href="#multiple-events-competing-risks" id="toc-multiple-events-competing-risks" class="nav-link" data-scroll-target="#multiple-events-competing-risks"><span class="header-section-number">2.4</span> Multiple events: competing risks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression with survival response</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="cox-proportional-hazards-model" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="cox-proportional-hazards-model"><span class="header-section-number">2.1</span> Cox proportional hazards model</h2>
<p>If survival time is of interest, such as in mortality studies, a common approach is to postulate a distribution for survival time and estimate the parameters of this distribution from the data. For instance, the exponential distribution can be used if the death rate is independent of time, the Weibull distribution allows for increasing or decreasing hazard rates, and the Gompertz distribution models hazard rates that exponentially increase or decrease over time.</p>
<p>More commonly, it is the relationship between survival time and one or more predictor variables (covariates) that is of interest. The Cox proportional hazards model is a widely used semi-parametric model to study this relationship. It is used to estimate the hazard ratio for individuals based on their covariates, without needing to specify the baseline hazard function.</p>
<p>Estimation of <span class="math inline">\(\boldsymbol{\beta}\)</span> and inferences are developed by considering the information supplied at each time that a death (event) occurred.</p>
<p>Consider:</p>
<ul>
<li>a death occurring at time <span class="math inline">\(t_j\)</span>, and</li>
<li>suppose that there were <span class="math inline">\(n_j\)</span> subjects alive just before <span class="math inline">\(t_j\)</span>,</li>
<li>that the values of <span class="math inline">\(\boldsymbol{x}\)</span> for these subjects are <span class="math inline">\(\boldsymbol{x_1}, \boldsymbol{x_2}, \cdots, \boldsymbol{x_{n'j}}\)</span></li>
<li>and that the subject that dies is denoted, by the subscript 1</li>
</ul>
<p>Then:</p>
<ul>
<li>The set of <span class="math inline">\(n'_j\)</span> subjects at risk is referred to as the <em>risk set</em>.</li>
<li>The risk of death at time <span class="math inline">\(t_j\)</span> for each subject in the risk set is given by: <span class="math display">\[h(t) = h_0(t)\textrm{exp}(\boldsymbol{\beta}^T\boldsymbol{x})\]</span></li>
</ul>
<p>where:</p>
<ul>
<li><span class="math inline">\(\boldsymbol{\beta}^T\boldsymbol{x}\)</span> is the matrix representation of the regression function, <span class="math inline">\(\beta_1x_1 + \beta_2x_2 + \cdots + \beta_px_p\)</span></li>
<li>and <span class="math inline">\(h_0(t)\)</span> is <strong>baseline hazard function</strong></li>
</ul>
<p>The risk of death at time <span class="math inline">\(t_j\)</span> in the risk set does not supply absolute measures of risk, but does supply the relative risks for each subject, since, although <span class="math inline">\(h_0(t)\)</span> is unknown, it is the same for each subject. Thus the probability that the death observed at <span class="math inline">\(t_j\)</span> was of the subject who did die at that time is: <span class="math display">\[p_j = \frac{\textrm{exp}(\boldsymbol{\beta}^T\boldsymbol{x_1})}{\sum \textrm{exp}(\beta^T\boldsymbol{x_i})}\]</span> where summation is over all remembers of the risk set.</p>
<p>Similar terms are derived for each time that a death occurred and are combined to form a likelihood (product of these probabilities over all event times <span class="math inline">\(t_j\)</span>): <span class="math display">\[PL(\boldsymbol{\beta}) = \prod_{j=1}^{k} \frac{\exp(\boldsymbol{\beta}^T \boldsymbol{x_1})}{\sum_{i \in \text{risk set at } t_j} \exp(\boldsymbol{\beta}^T \boldsymbol{x_i})}\]</span> Technically this is called <em>partial likelihood</em>, since the component terms are derived conditionally on the times that deaths occurred and the composition of the risk set at these times. This partial likelihood is used to estimate the regression coefficients <span class="math inline">\(\boldsymbol{\beta}\)</span> in the Cox model. Maximizing this partial likelihood gives the best estimates for <span class="math inline">\(\boldsymbol{\beta}\)</span>, quantifying the effect of the covariates on the hazard.</p>
<p>To estimate <span class="math inline">\(\beta\)</span>, we maximize the partial likelihood function with respect to <span class="math inline">\(\beta\)</span>. No closed-form solution is available, and so iterative algorithms are used.</p>
</section>
<section id="example-with-brain-cancer-data" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="example-with-brain-cancer-data"><span class="header-section-number">2.2</span> Example with brain cancer data</h2>
<p>The <code>BrainCancer</code> data set from the <code>ISLR2</code> package contains survival times for patients with primary brain tumors undergoing treatment with radiation therapy. Variables included in the study are:</p>
<ul>
<li><code>sex</code>: male or female</li>
<li><code>diagnosis</code>: meningioma, LG glioma, HG glioma, or other</li>
<li><code>loc</code>: tumor location, infratentorial or supratentorial</li>
<li><code>gtv</code>: gross tumor volume <span class="math inline">\(cm^3\)</span></li>
<li><code>ki</code>: Karnofsky index</li>
<li><code>stereo</code>: stereotatcic radiosurgery (SRS) or fractionated stereotactic (SRT) radiotherapy</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># preview data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data_brain <span class="ot">&lt;-</span> BrainCancer</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>data_brain <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   88 obs. of  8 variables:
 $ sex      : Factor w/ 2 levels "Female","Male": 1 2 1 1 2 1 2 2 1 2 ...
 $ diagnosis: Factor w/ 4 levels "Meningioma","LG glioma",..: 1 3 1 2 3 1 1 2 1 3 ...
 $ loc      : Factor w/ 2 levels "Infratentorial",..: 1 2 1 2 2 2 2 2 2 2 ...
 $ ki       : int  90 90 70 80 90 80 80 80 70 100 ...
 $ gtv      : num  6.11 19.35 7.95 7.61 5.06 ...
 $ stereo   : Factor w/ 2 levels "SRS","SRT": 1 2 1 2 2 1 2 2 2 2 ...
 $ status   : int  0 1 0 1 1 0 0 0 0 0 ...
 $ time     : num  57.64 8.98 26.46 47.8 6.3 ...</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cox model with multiple predictors</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>fit.cox_multi <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> sex <span class="sc">+</span> diagnosis <span class="sc">+</span> ki, <span class="at">data =</span> data_brain)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.cox_multi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, status) ~ sex + diagnosis + ki, data = data_brain)

  n= 87, number of events= 35 
   (1 observation deleted due to missingness)

                       coef exp(coef) se(coef)      z Pr(&gt;|z|)    
sexMale             0.11149   1.11795  0.35670  0.313 0.754608    
diagnosisLG glioma  1.01441   2.75774  0.62159  1.632 0.102687    
diagnosisHG glioma  2.22962   9.29629  0.44520  5.008  5.5e-07 ***
diagnosisOther      0.82773   2.28813  0.57751  1.433 0.151774    
ki                 -0.06624   0.93591  0.01753 -3.778 0.000158 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

                   exp(coef) exp(-coef) lower .95 upper .95
sexMale               1.1179     0.8945    0.5556    2.2493
diagnosisLG glioma    2.7577     0.3626    0.8156    9.3251
diagnosisHG glioma    9.2963     0.1076    3.8847   22.2467
diagnosisOther        2.2881     0.4370    0.7377    7.0967
ki                    0.9359     1.0685    0.9043    0.9686

Concordance= 0.782  (se = 0.038 )
Likelihood ratio test= 36.59  on 5 df,   p=7e-07
Wald test            = 34.11  on 5 df,   p=2e-06
Score (logrank) test = 40.79  on 5 df,   p=1e-07</code></pre>
</div>
</div>
<section id="coefficient-interpration" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="coefficient-interpration"><span class="header-section-number">2.2.1</span> Coefficient interpration</h3>
<p>Above, we fitted Cox model using <code>sex</code> and <code>diagnosis</code> as predictors. The results, indicate, for instance that:</p>
<ul>
<li>The estimated hazard ratio (HR) for a male patient is <span class="math inline">\(e^{0.11} = 1.11\)</span>. This means that men have 1.11 times the hazard of dying than women while keeping other variables constant (sometimes referred to as adjusted hazard ration, AHR).</li>
<li>However the associated Z value is small, resulting in large p-value of 0.75, which indicates that this difference is not statistically significant.</li>
<li>We can also see that one-unit increase in the Karnofsky index is corresponds to a multiplier of <span class="math inline">\(e^{-0.06} = 0.94\)</span> in the chance of dying. The higher the Karnofsky index score, the lower the chance of dying at any given point in time, with this effect being highly significant <span class="math inline">\(p\)</span>-value of 0.000158.</li>
<li>Note that if you want to find HR associated with more than 1-unit dffererence, e.g.&nbsp;for patients with 10 units higher Karnofsky index, we would calculate HR as <span class="math inline">\(e^{-0.06 \times 10} = 0.54\)</span>. This means that patients with 10 units higher Karnofsky index have 0.54 times the hazard of dying compared to those with lower Karnofsky index.</li>
</ul>
<p>Sometimes, in addition to reporting the numeric results of a Cox regression, <strong>forest plots</strong> are used to visualize HRs and their 95% confidence intervals.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make forest plot with ggforest()</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggforest</span>(fit.cox_multi, <span class="at">data =</span> data_brain)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/forest-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="global-statistical-signficance" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="global-statistical-signficance"><span class="header-section-number">2.2.2</span> Global statistical signficance</h3>
<p>The output of the Cox regression contains also three methods for an overall test of whether the predictors in the model have a significant effect on the hazard (or risk) of the event occurring. Essentially, these check whether the model as a whole provides a better fit than a null model (a model without any covariates).</p>
<p><strong>Likelihood Ratio Test (LRT)</strong> compares the log-likelihoods of two models:</p>
<ul>
<li>The <strong>null model</strong>, which includes only the baseline hazard (i.e., no covariates).</li>
<li>The <strong>full model</strong>, which includes the covariates of interest.</li>
</ul>
<p>The test statistic is computed as: <span class="math display">\[
2 \times (\text{log-likelihood of the full model} - \text{log-likelihood of the null model})
\]</span> This statistic follows a chi-squared distribution, and the associated p-value indicates whether the full model (with covariates) is significantly better at explaining the data than the null model.</p>
<p><strong>Wald Test</strong></p>
<p>The Wald test checks whether the estimated regression coefficients are significantly different from zero. For each predictor, the test examines whether its coefficient, <span class="math inline">\(\beta_i\)</span>, is significantly different from 0, implying that the predictor has a significant effect on the hazard. The Wald test can also be used as a global test of significance.</p>
<p><strong>Score Test (Log-Rank Test)</strong></p>
<p>The Score test (also called the log-rank test in this context) evaluates the contribution of each predictor to the model’s fit, considering the expected number of events. Like the likelihood ratio test, the Score test also compares the null and full models and uses a chi-squared distribution to compute significance.</p>
</section>
<section id="concordance" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="concordance"><span class="header-section-number">2.2.3</span> Concordance</h3>
<p>In the context of a <strong>Cox proportional hazards model</strong>, <strong>concordance</strong> (also known as the <strong>C-index</strong> or <strong>concordance index</strong>) is a measure of how well the model predicts the order of events. Specifically, it assesses the ability of the Cox model to correctly predict which of two individuals will experience an event first, based on their risk scores.</p>
<p>The <strong>concordance index</strong> (C-index) ranges between 0.5 and 1:</p>
<ul>
<li>A <strong>C-index of 0.5</strong> indicates that the model’s predictions are no better than random chance. This means the model cannot distinguish between individuals who experience the event earlier and those who experience it later.</li>
<li>A <strong>C-index of 1</strong> means perfect prediction, indicating that the model always correctly predicts the order of events.</li>
</ul>
<p>The C-index is similar to the <strong>area under the ROC curve (AUC)</strong> used in binary classification models, but it is adapted to survival analysis where the goal is to rank individuals by their risk of experiencing the event.</p>
<p>In our example, a concordance of 0.782 means that the Cox model can correctly predict the ordering of survival times 78.2% of the time. In other words, if you randomly select two individuals and compare their predicted risk scores, the model will correctly predict which individual experiences the event earlier in 78.2% of cases. The standard error is 0.038 which provides a measure of uncertainty around the concordance estimate. A smaller standard error indicates more confidence in the estimate.</p>
</section>
<section id="predictions" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="predictions"><span class="header-section-number">2.2.4</span> Predictions</h3>
<p>In Cox regression, we can estimate:</p>
<ul>
<li>the survival probability at a specific time, <span class="math inline">\(S(t|X=x)\)</span></li>
<li>and the hazard ratio for an individual relative to a reference individual, $h(t|X=x) / <span class="math inline">\(S(t|X=x_{ref})\)</span>, where <span class="math inline">\(X_{ref}\)</span> is a reference individual with known covariate values.</li>
</ul>
<p>For predicted survival, the choice of time matters. A predicted HR will not depend on time due to proportional hazards assumption.</p>
<section id="survival" class="level4" data-number="2.2.4.1">
<h4 data-number="2.2.4.1" class="anchored" data-anchor-id="survival"><span class="header-section-number">2.2.4.1</span> Survival</h4>
<p>Let’s predict the probability of survival at 40 days, for a new patient (man, with LG glioma, Karnofsky index of 80).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># new patient data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>new_pat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time =</span> <span class="dv">40</span>, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sex =</span> <span class="st">"Male"</span>, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">diagnosis =</span> <span class="st">"LG glioma"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ki =</span> <span class="dv">80</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">status =</span> <span class="dv">0</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit.cox_multi, <span class="at">newdata =</span> new_pat, <span class="at">type =</span> <span class="st">"survival"</span>, <span class="at">se.fit =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$fit
[1] 0.4824421

$se.fit
[1] 0.1834607</code></pre>
</div>
</div>
<p>The probability of surviving through 40 days is 0.48. To get confidence interval we could use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unlist</span>(<span class="fu">summary</span>(<span class="fu">survfit</span>(fit.cox_multi,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">newdata =</span> new_pat,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">se.fit =</span>T, <span class="at">conf.int =</span> <span class="fl">0.95</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">times=</span><span class="dv">40</span>)[<span class="fu">c</span>(<span class="st">"surv"</span>, <span class="st">"std.err"</span>, <span class="st">"lower"</span>, <span class="st">"upper"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     surv   std.err     lower     upper 
0.4824421 0.1834607 0.2289573 1.0000000 </code></pre>
</div>
</div>
<p>So the probability of surviving through 40 days is 0.48 with 95% CI [0.23, 1].</p>
</section>
<section id="hr" class="level4" data-number="2.2.4.2">
<h4 data-number="2.2.4.2" class="anchored" data-anchor-id="hr"><span class="header-section-number">2.2.4.2</span> HR</h4>
<p>To predict the adjusted hazard ratio for a new patient, we use again the <code>predict()</code> function, this type with <code>type = "risk"</code>. We also need to specify the reference individual. Some options include:</p>
<ul>
<li><code>reference = "zero"</code>: the reference individual has continuous predictor values set to 0 and categorical predictors each at their reference level. This is not a good choice if a value of 0 is not plausible for continuous variables in the model, e.g.&nbsp;age.</li>
<li><code>reference = "sample"</code>: the reference individual has continuous predictors each their respective sample mean and categorical predictors at their reference level.</li>
<li><code>reference = "strata"</code>: this leads to the same results as in <code>reference = "sample" unless the model includes a</code>strata()`, in which case continuous variables will be set their within-stratum means.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict HR for our new patient</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit.cox_multi, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">newdata =</span> new_pat, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">"risk"</span>, </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">reference =</span> <span class="st">"strata"</span>, </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">se.fit =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$fit
       1 
3.276632 

$se.fit
       1 
1.201369 </code></pre>
</div>
</div>
<p>Our new patient 3.27 times the hazard of dying compared to a reference individual with level of each categorical predictor and the mean of each continuous predictor, which in our case are (Female for gender, Meningioma for diagnosis, and mean Karnofsky index of 81.02).</p>
</section>
</section>
</section>
<section id="time-dependent-covariates" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="time-dependent-covariates"><span class="header-section-number">2.3</span> Time-dependent covariates</h2>
<p>In all above example the predictors did not vary over time. Each individual had only one value for each predictor. Since survival data is the result of follow-up over time, it is possible to have predictors that do vary over time. For example, in a study of time to heart attack, researchers could record various other conditions’ occurrence over time, such as hypertension or angina. In a study of juvenile recidivism, researchers could record how education or employment status change over time. Cox regression is able to handle such time-varying predictors (also known as “time dependent covariates”).</p>
<p>For time-varying covariates, the hazard function is extended to account for changes in the covariates over time: <span class="math display">\[h(t | \boldsymbol{x}(t)) = h_0(t) \cdot \exp\left(\boldsymbol{\beta}^T \boldsymbol{x}(t)\right)\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(h(t | \boldsymbol{x}(t))\)</span> is the hazard at time <span class="math inline">\(t\)</span>, conditional on the covariate values at that time.</li>
<li><span class="math inline">\(\boldsymbol{x}(t)\)</span> represents the covariate vector at time <span class="math inline">\(t\)</span>. In this case, one or more covariates can change over time.</li>
<li><span class="math inline">\(\boldsymbol{\beta}\)</span> is the vector of regression coefficients.</li>
<li><span class="math inline">\(h_0(t)\)</span> is the baseline hazard function, which remains time-dependent but does not depend on the covariates.</li>
</ul>
<p>In practice, time-varying covariates are handled by breaking the follow-up time into intervals where the covariate values are assumed to remain constant, and then updating the covariate values at each interval. Suppose a covariate (e.g., blood pressure, treatment status, or exposure) varies over time. For an individual, we divide their follow-up time into periods where the covariate value is constant, and then treat each period as a separate “observation” in the Cox model. The Cox model then uses these updated covariate values when estimating the hazard at each time point.</p>
<p>The partial likelihood function in the Cox model is modified to incorporate the updated covariate values <span class="math inline">\(\boldsymbol{x}(t)\)</span>. For each event time <span class="math inline">\(t_j\)</span>, the likelihood is based on the covariate values that are valid at that specific time.</p>
<p>The partial likelihood becomes:</p>
<p><span class="math display">\[PL(\boldsymbol{\beta}) = \prod_{j=1}^{k} \frac{\exp\left(\boldsymbol{\beta}^T \boldsymbol{x}_1(t_j)\right)}{\sum_{i \in \text{risk set at } t_j} \exp\left(\boldsymbol{\beta}^T \boldsymbol{x}_i(t_j)\right)}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\boldsymbol{x}_1(t_j)\)</span> is the covariate vector for the subject who experienced the event at time <span class="math inline">\(t_j\)</span>,</li>
<li>and <span class="math inline">\(\boldsymbol{x}_i(t_j)\)</span> is the covariate vector for each subject in the risk set at time <span class="math inline">\(t_j\)</span>.</li>
</ul>
<p>A dataset with time-varying predictors will have multiple rows per individual, with different rows having different values for the time-varying predictors, reflecting how they change over time. Additionally, rather than having a single event time variable, each row will have two time variables indicating the beginning and end of the time interval represented by that row of data.</p>
<p>For instance, in the study of heroin usage, we can see a male participant who started using non-prescribed pharmaceutical opioids (NPPOs) at age 19 (time independent covariates). He did not meet the criteria for lifetime opioid dependence at baseline (wave 1), but did at the next interview (wave2), and he first reported using heroin at his 6th interview (both time varying variables).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data_opioid <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/data-opioid.rds"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>data_opioid <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(RANDID <span class="sc">==</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(RANDID, wave, START, STOP, heroin, age_at_init, sex, dep_lifetime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  RANDID wave START STOP heroin age_at_init  sex dep_lifetime
1     10    1  3.78 4.26      0          19 Male            0
2     10    2  4.26 4.78      0          19 Male            1
3     10    3  4.78 5.29      0          19 Male            1
4     10    4  5.29 5.84      0          19 Male            1
5     10    5  5.84 6.27      0          19 Male            1
6     10    6  6.27 6.79      1          19 Male            1</code></pre>
</div>
</div>
</section>
<section id="multiple-events-competing-risks" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="multiple-events-competing-risks"><span class="header-section-number">2.4</span> Multiple events: competing risks</h2>
<p>In survival analysis, <strong>competing risks</strong> occur when an individual is at risk of more than one mutually exclusive event, and the occurrence of one event <strong>precludes</strong> the occurrence of the others. Traditional survival models, such as the <strong>Cox proportional hazards model</strong>, typically focus on a single type of event (e.g., death or failure), but in many real-world scenarios, individuals may face different types of events that compete with each other.</p>
<p>A <strong>competing risk</strong> refers to events that prevent the event of primary interest from happening. For example: - In a study of heart disease, <strong>death due to cancer</strong> is a competing risk if the primary event of interest is <strong>death due to heart disease</strong>. - In a study of cancer treatment, <strong>death from any cause</strong> is a competing risk if the event of interest is <strong>relapse</strong>.</p>
<p>In these situations, standard survival analysis methods may overestimate the probability of the primary event because they do not account for the possibility of competing events.</p>
<p><strong>The Cumulative Incidence Function (CIF)</strong> is commonly used in competing risks analysis. It represents the probability of experiencing a specific event (e.g., death from heart disease) by a certain time, accounting for the presence of competing risks (e.g., death from cancer).</p>
<p>CIF is a product of two estimates.</p>
<ol type="1">
<li>The estimate of hazard at ordered failure time <span class="math inline">\(t_j\)</span> for the event of interest: <span class="math display">\[\hat{h_c(t_j)}=\frac{d_{cj}}{n_j}\]</span> where:</li>
</ol>
<ul>
<li><span class="math inline">\(m_{cj}\)</span> denotes the number of events for risk <span class="math inline">\(c\)</span> at time <span class="math inline">\(t_j\)</span></li>
<li>and <span class="math inline">\(n_j\)</span> is the number of subjects at risk at time <span class="math inline">\(t_j\)</span></li>
</ul>
<ol start="2" type="1">
<li>The estimate of overall probability of surviving previous time: <span class="math display">\[\hat{S}(t_{j-1})\]</span> We consider the overall survival as a subject must have survived all other competing events in order to fail from event type <span class="math inline">\(c\)</span> at time <span class="math inline">\(t_j\)</span>.</li>
</ol>
<p>The estimated incidence probability of failing from even type <span class="math inline">\(c\)</span> at time <span class="math inline">\(t_j\)</span> is then: <span class="math display">\[\hat{I_c}(t_j) = \hat{S}(t_{j-1}) \times \hat{h_c(t_j)}\]</span> The probability of failing form even type <span class="math inline">\(c\)</span> at time <span class="math inline">\(t_j\)</span> is a product of surviving the previous time periods and the cause specific hazard at time <span class="math inline">\(t_j\)</span>.</p>
<p>The CIF for event type <span class="math inline">\(c\)</span> at time <span class="math inline">\(t_j\)</span> is then the cumulative sum up to time <span class="math inline">\(t_j\)</span>, i.e.&nbsp;from <span class="math inline">\(f' = 1\)</span> to <span class="math inline">\(f'=f\)</span>, of these incidence probabilities over all event type <span class="math inline">\(c\)</span> failure times, which is expressed: <span class="math display">\[CIF_c(t_j) = \sum_{f'=1}^{f}\hat{I_c}(t_j) = \sum_{f'=1}^{f}\hat{S}(t_{f'-1})\times\hat{h_c}(t_{f'})\]</span></p>
<p>In 1999 <span class="citation" data-cites="Gray1998">Gray (<a href="references.html#ref-Gray1998" role="doc-biblioref">1998</a>)</span> proposed a non-parametric test to compare two or more CIFs. The test is analogous to the log-rank test comparing KM curves, using a modified Chi-squared test statistic. This test does not require the independent censoring assumption.</p>
<p>In Fine and Gray <span class="citation" data-cites="Fine1999">Fine and Gray (<a href="references.html#ref-Fine1999" role="doc-biblioref">1999</a>)</span> proposed a proportional hazards model aims at modeling the CIF with covariates, by treating the CIF curve as a subdistribution function. The subdistribution function is analogous to the Cox proportional hazard model, except that it models a hazard function (as known as subdistribution hazard) derived from a CIF.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Fine1999" class="csl-entry" role="listitem">
Fine, Jason P., and Robert J. Gray. 1999. <span>“A Proportional Hazards Model for the Subdistribution of a Competing Risk.”</span> <em>Journal of the American Statistical Association</em> 94. <a href="https://doi.org/10.1080/01621459.1999.10474144">https://doi.org/10.1080/01621459.1999.10474144</a>.
</div>
<div id="ref-Gray1998" class="csl-entry" role="listitem">
Gray, Robert J. 1998. <span>“A Class of k-Sample Tests for Comparing the Cumulative Incidence of a Competing Risk.”</span> <em>The Annals of Statistics</em> 16. <a href="https://doi.org/10.1214/aos/1176350951">https://doi.org/10.1214/aos/1176350951</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lab.html" class="pagination-link" aria-label="R examples">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R examples</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>