---
title: "Test yourself 01"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


Rate your confidence of being able to answer the below questions saying A, B or C, where:

- A. I am confident that I do not know the answer to this question
- B. I know at least 50% of the answer to this question, within 20 minutes I could find the required resources to enable a complete answer
- C. I am not confident that I can answer the question at this time.


### Part I

1. Could you write out explicitly what is meant by the following: 
$$\prod_{n=1}^{3}(n+x)$$
2. Could you write down the result of below matrix multiplication? 
$$\begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} \times \begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} $$
3. Could you explain what a random variable is? 

4. Given  Bernoulli, Poisson, Normal and $\chi^2$ distributions could you tell which are discrete and which are continuous?

5. Could you simulate in R tossing an unbiased coin using sample() function?

6. Could you give examples of a probability mass function and density mass function?

7. Let $Z \sim N(0,1)$ be a standard normal variable, could you calculate $P(Z < 1.12)$?

8. Could you explain central limit theorem? 

### Part II


1. What is meant explicitly by the following: 
$\prod_{n=1}^{3}(n+x)$
a) $(1+x)(2+x)(3+x)$
b) $(0+x)(1+x)(2+x)(3+x)$
c) $(n+1)(n+2)(n03$
d) none of the above

-----

2. What is the results the of the below matrix multiplication? 
$$\begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} \times \begin{bmatrix} 1 & 2  \\ 3 & 4 \end{bmatrix} $$

a) $$\begin{bmatrix} 1 & 4  \\ 9 & 16 \end{bmatrix}$$
b) $$\begin{bmatrix} 7 & 10  \\ 15 & 22 \end{bmatrix}$$
c) $$\begin{bmatrix} 7 & 15  \\ 10 & 22 \end{bmatrix}$$
d) it is not possible to multiple as the matrix are not rectangular

-----

3. When rolling a six-sided dice, a random variable could be:
a) the number of 6 when rolling dice 100 times
b) the outcome of each individual roll
c) the probability of getting 6
d) the possible outcomes of the roll, that is 1,2,3,4,5 and 6

-----

4. Given Bernoulli, Poisson, Normal and $\chi^2$  distributions what is true?
a) Bernoulli is discrete while Poisson, Normal and $\chi^2$  are continuous
b) Normal and $\chi^2$  are continuous while Bernoulli and Poisson are discrete 
c) Normal is the only one continuous
d) Bernoulli and Poisson are continuous, Normal and $\chi^2$  are discrete

-----

5. Which command is correct to simulate tossing an unbiased coin 10 times?

```{r, eval=F}
a) replicate(5, sample(c("H", "T"), size=2, replace=FALSE))

b) sample(c("H", "T"), size=10, replace=TRUE)

c) sample(c("H", "T", "H", "T", "H", "T", "H", "T","H", "T"), size=1, replace=FALSE)

d) replicate(10, sample(c("H", "T"), size=10, replace=TRUE))
```

-----

6. What is true about probability mass function and density mass function? 

a) probability mass function cam be provided summarized in a table for a continuous random variable
b) probability density function can be provided summarized in a table for a continuous random variable
c) probability mass function cam be provided summarized in table for a discrete random variable
d) probability density function can be provided summarized in a table for a discrete random variable

-----

7. Let $Z \sim N(0,1)$ be a standard normal variable, what is $P(Z < 1.12)$?
a) 0.131
b) 0.869
c) 0.768
d) none of the above

-----

8. Which is true regarding central limit theorem? 
a) everything in nature follows normal distribution
b) the sum of independent and equally distributed random observation is normally distributed if large enough
c) the sum of independent and equally distributed random variables is normally distributed if large enough
d) the sum of random variables is normally distributed if large enough

