---
title: "Test yourself 02"
output:
  html_document: default
  pdf_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---


Rate your confidence of being able to answer the below questions saying A, B or C, where:

- A. I am confident that I know the answer to this question
- B. I know at least 50% of the answer to this question, within 20 minutes I could find the required resources to enable a complete answer
- C. I am not confident that I can answer the question at this time.


### Part I

1. Given example data, could you recognize data types such as nominal, ordinal, discrete and continuous?

2. Knowing that height [cm] in population is normally distributed with $\mu = 170$ and $\sigma = 10$, you measure height of 4 friends at the random party. Could you calculate the probability of seeing a sample mean of 180 cm or higher?

3. Given that the height [cm] in population is normally distributed with $\mu = 170$ and $\sigma = 10$ and a height of 4 people in your group is 170, 172, 180, 177 could you compute SEM, the standard error of mean? 

4. In hypothesis testing, could you explain the difference between $H_0$ and $H_a$?

5. A gardening enthusiast is interested in knowing whether pea plant grow better in one part of the garden than in the other. One spring he plants 5 plants in parcel A and 5 plants in B and notes throughout the summer the number of peas collected. He gets 101, 100, 99, 120, 111 green peas from plants in parcel A and 111, 105, 130, 110, 120 in parcel B. Assuming unequal variance, could you use t-test to check if parcel B is producing more peas? 

6. A scale has a normally distributed error with mean 0 and standard deviation 1. You measure a sample 10 times and observe the mean weight of 50. Could you find out the t value to construct the 99% confidence interval of the sample weight? 

7. Could you explain the difference between type I and type II errors? 

8. In hypothesis testing, could you explain why we may use resampling techniques?


### Part II

1. As part of a cancer study researchers have access to data including cancer stage (0, I, II, III and IV), gender (male/female), age in years and number of hospital visits. What is true about the data type?
a) cancer stage and gender are nominal while age and number of beds are continuous 
b) cancer stage is nominal, gender is ordinal, gender is discrete and number of visits is discrete
c) cancer stage is ordinal, gender is nominal, age and number of visits are discrete
d) none of the above

2. Knowing that height [cm] in population is normally distributed with $\mu = 170$ and $\sigma = 10$, you measure height of 4 friends at the random party. What is the probability of seeing a sample mean of 180 cm or higher?
a) 0.159
b) 0.023
c) 0.000
d) 0.977

3. Given that the height [cm] in population is normally distributed with $\mu = 170$ and $\sigma = 10$ and a height of 4 people in your group is 170, 172, 180, 177 compute SEM, the standard error of mean? 
a) 0.915
b) 5
c) 4
d) none of the above

4. In hypothesis testing, what is true about $H_0$ and $H_1$?
a) $H_0$ is the null hypothesis that we reject in favor of $H_1$ if there is enough evidence given the collected data
b) $H_1$ is a general neutral hypothesis such as "no change" or "no difference between groups"
c) $H_0$ is a null hypothesis of "no change", $H_1$ is the alternative, we do not need $H_1$ if we want to accept $H_0$ there is "no change"
d) $H_0$ is a null hypothesis and $H_1$ is alternative hypothesis that we either reject or accept depending on the evidence in the data collected

5. A gardening enthusiast is interested in knowing whether pea plant grow better in one part of the garden than in the other. One spring he plants 5 plants in parcel A and 5 plants in B and notes throughout the summer the number of peas collected. He gets 101, 100, 99, 120, 111 green peas from plants in parcel A and 111, 105, 130, 110, 120 in parcel B. Assuming unequal variance, what is t-test statistics to obtained when checking if parcel B is producing more peas? 
a) -1.4983,
b) 7.9451
c) 0.9137
d) 0.1727

6. A scale has a normally distributed error with mean 0 and standard deviation 1. You measure a sample 10 times and observe the mean weight of 50. What is t value to construct the 99% confidence interval of the sample weight? 
a) 2.262
b) 3.250
c) 3.169
d) 2.228

7. Which one is not correct about type I and type II errors?
a) type I error is the rejection of a true null hypothesis
b) type II error is the non-rejection of a false null hypothesis 
c) type I is the rejection of a true null hypothesis
d) type I can be viewed as "false alarm"

8. In hypothesis testing, what is true about resampling techniques?
a) when we do not know the distribution we use resampling to obtain sampling distributions
b) we use resampling to avoid mathematical computations
c) we can use resampling or parametric test, they yield the same results 
d) when the data does not follow normal distribution we use resampling techniques






