project:
  type: book
  output-dir: docs

book:
  title: "Mathmetical foundations"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - math-notations.qmd
    - math-sets.qmd
    - math-functions.qmd
    - math-differentiation.qmd
    - math-integration.qmd
    - math-vectors.qmd
    - math-matrix.qmd
    #- exercises.qmd
    
bibliography: references.bib


format:
  html:
    theme: spacebar
    code-fold: true
    mermaid:
      theme: forest

    
    


