---
title: "Mathematical foundations"
author: "Olga Dethlefsen"
site: bookdown::bookdown_site
documentclass: book
date: "`r Sys.Date()`"  
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Mathematical foundations"
---

# Preface {-}

This repository contains teaching and learning materials prepared and used during "Introduction to biostatistics and machine learning" course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. More about the course [https://uppsala.instructure.com/courses/51998/](https://uppsala.instructure.com/courses/51998/) 

Do you see a mistake or a typo? I would be grateful if you let me know via [olga.dethlefsen@nbis.se](olga.dethlefsen@nbis.se)


# Acknowledgments {-}
Thank you to everyone helping out to make these materials better. A warm thank you goes to: 
Eva Freyhult, Payam Emami, Mun-Gwan Hong, Nima Rafati, Cecilia Hellstr$\ddot o$m, Oliver Konzock, Franziska Hildebrandt.


