# Preface {.unnumbered}

Biostatistics and Machine Learning are based on mathematics. The purpose of this pre-course is to capture some basic notations and conventions used.

**Aims**

- to capture basic mathematical notations and conventions used in mathematics
- and provide revision materials

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared for and used during “Introduction to biostatistics and Machine Learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use the basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*

## Acknowledgments {-}

Thank you to everyone helping out to make these materials better. A warm thank you goes to: 
Eva Freyhult, Payam Emami, Mun-Gwan Hong, Nima Rafati, Cecilia Hellstr$\ddot o$m, Oliver Konzock, Franziska Hildebrandt, Jonas Andersson.


