
## Quiz

::: {#exr-m-notations-numbers}

### Types of numbers

Match number to its type and explanation. Use only once every type and explanation from the right hand side list. 

- 4: natural number (N), also a subset of integers (Z)
- 4.4: real number (R), rational as it can be expressed as a ratio of two integers
- $\sqrt5$: real number (R), irrational (P), cannot be written as a ratio of two integers
- 4: integer (Z)

Distractors: 

- integer (Z), also a subset of natural numbers (N)
- real number (R), irrational (P) as it can be expressed as a fraction of two integers
- integer(Z), also a subset of whole numbers (W)

:::


::: {#exr-integrals}

$\int_0^{10} x \cdot dx$

:::

::: {.solution}
@exr-integrals
:::

$\int_0^{10} x \cdot dx = \Bigr[\frac{x^2}{2}]_0^{10}=\frac{10^2}{2} - \frac{0^2}{2} = 50$


::: {#exr-m-notations-sigma-product}

### Expand Sigma and Pi

Write out explicitly what is meant by the following:

a) $\displaystyle \sum_{i=1}^{i=6}k_i$

b) $\displaystyle \prod_{i=1}^{i=6}k_i$

c) $\displaystyle \sum_{i=1}^{i=6}i^k$

d) $\displaystyle \prod_{i=1}^{i=3}i^k$

e) $\displaystyle \sum_{i=1}^{n}i$

f) $\displaystyle \sum_{i=1}^{i=4}(i + 1)^k$

g) $\displaystyle \prod_{i=1}^{i=4}(k + 1)^i$

h) $\displaystyle \prod_{i=0}^{n}i$

:::

::: {#exr-m-notations-sigma-product-reverse}

### Write in Sigma and Pi

Use Sigma or Product notation to represent the long sums and products below:
  
a) $1+2+3+4+5+6$
b) $2^2+3^2+4^2+5^2$
c) $4 \cdot 5 \cdot 6 \cdot 7 \cdot 8$
d) $1 + \frac{1}{2} + \frac{1}{3} + \frac{1}{4} + \frac{1}{5} +...+ \frac{1}{n}$
e) $2-2^2+2^3-2^4 + ...+2^n$
f) $3+6+9+12+···+60$
g) $3x + 6x^2 + 9x^3 + 12x^4 +...+60x^{20}$
h) $3x \cdot 6x^2 \cdot 9x^3 \cdot 12x^4 \cdot...\cdot 60x^{20}$

:::


## Answers {-}

::: {.solution}
@exr-m-notations-numbers
:::

a) real, rational
b) natural and integers, integers include natural numbers
c) $\sqrt{4} = 2$ so it is a natural number and/subset of integers
d) real number, rational as it could be written as $\frac{23}{10}$
e) real number, irrational as it cannot be explained by a simple fraction
f) real number, irrational as it cannot be explained by a simple fraction
g) integer, non a natural number as these do not include negative numbers
h) natural number, although there is some argument about it as some define natural numbers as positive integers starting from 1, 2 etc. while others include 0.
i) real, rational number, could be written as $\frac{25}{100}$

::: {.solution}
@exr-m-notations-variables-constants
:::

a) constant, speed of light in vacuum is a constant, denoted $c$ with $c=299 792 458 \frac{m}{s}$
b) variable, mass of an apple is a variable, different for different apple sizes, for instance 138 grams, denoted as $m = 100 g$
c) variable, like mass volume can be different from apple to apple, denoted as $V$, e.g. $V = 200 cm^3$
d) variable, like volume and mass can vary, denoted as $\rho_i$ and defined as $\rho_i=\frac{m}{V}$. So given 6.3 milligrams of vitamin C in our example apple, we have $\rho_i=\frac{0.0063}{2}\frac{g}{cm^3} = 0.0000315 \frac{g}{cm^3}$ concentration of vitamin D
e) constant, the distance between Stockholm and Uppsala is fixed; it could be a variable though if we were to consider an experiment on a very long time scale; distance is often denoted in physics as $d$
f) variable, time on the train to travel between the stations varies, often denoted as $t$ with speed being calculated as $s = \frac{d}{t}$
g) constant, electron charge is $e = 1.60217663\cdot10^{-19} C$

::: {.solution}
@exr-m-notations-sigma-product
:::

a) $\displaystyle \sum_{i=1}^{i=6}k_i = k_1 + k_2 + k_3 + k_4 + k_5 + k_6$

b) $\displaystyle \prod_{i=1}^{i=6}k_i = k_1 \cdot k_2 \cdot k_3 \cdot k_4 \cdot k_5 \cdot k_6$

c) $\displaystyle \sum_{i=1}^{i=3}i^k = 1^k + 2^k + 3^k$

d) $\displaystyle \prod_{i=1}^{i=3}i^k = 1^k \cdot 2^k \cdot 3^k$

e) $\displaystyle \sum_{i=1}^{n}i = 1 + 2 + 3 + ... + n$ we are using dots (...) to represent all the number until $n$. Here, thanks to Gauss we can also write $\displaystyle \sum_{i=1}^{n}i = \frac{n(n+1)}{2}$, i.e. Gauss formula for sum of first $n$ natural numbers

<!-- f) $\sum_{i=1}^{i=4}(i + 1)^k = (1+1)^k + (2+1)^k + (3+1)^k + (4+1)^k$ -->

<!-- g) $\prod_{i=1}^{i=4}(k + 1)^i = (k+1)^1 \cdot (k+2)^k \cdot (k+3)^k \cdot (k+4)^k$ -->

<!-- h) $\prod_{i=0}^{n}i = 0 \cdot 1 \cdot 2 \cdot ... \cdot n$ which is actually $\prod_{i=0}^{n}i = 0$ as anything multiplied by 0 is 0 -->

::: {.solution}
@exr-m-notations-sigma-product-reverse
:::

a) $1+2+3+4+5+6 = \displaystyle \sum_{k=1}^{6}k$

b) $2^2+3^2+4^2+5^2 = \displaystyle \sum_{x=2}^{5}x^2$

c) $4 \cdot 5 \cdot 6 \cdot 7 \cdot 8 = \displaystyle \prod_{x=4}^{8}x$

d) $1 + \frac{1}{2} + \frac{1}{3} + \frac{1}{4} + \frac{1}{5} + ... + \frac{1}{n} = \displaystyle \sum_{k=1}^{n}\frac{1}{k}$

<!-- e) $2-2^2+2^3−2^4+...+2^n = \sum_{n=1}^{n} (-1)^n \cdot 2^n$ -->

<!-- f) $3+6+9+12+···+60 = \sum_{n=1}^{30}3\cdot n$ -->

<!-- g) $3x + 6x^2 + 9x^3 + 12x^4 +...+60^{20} = \sum_{n=1}^{20}3 \cdot n \cdot x^n$ -->

<!-- h) $3x \cdot 6x^2 \cdot 9x^3 \cdot 12x^4 \cdot...\cdot60^{20} = \prod_{n=1}^{20}3 \cdot n \cdot x^n$ -->
