---
title: "Exercises: Random sample"
date: "2022-09-12"
output: bookdown::html_document2
---

```{exercise, label="cholesterol", echo=TRUE}
**Exercise in distribution of sample mean**
  
  The total cholesterol in population (mg/dL) is normally distributed with $\mu = 202$ and $\sigma = 40$.
  
  a. How is the sample mean of a sample of 4 persons distributed?
  b. What is the probability to see a sample mean of 260 mg/dL or higher?
  c. Is there reason to believe that the four persons with mean 260 mg/dL were sampled from another population with higher population mean?
```

*Solution*

a. $$\bar X = \frac{1}{4}\sum_{i=1}^4 X_i \\
X_i \sim N(\mu, \sigma) \\
\bar X \sim N\left(\mu, \frac{\sigma}{\sqrt{n}}\right) = N(202, 20)
$$
b. 0.0019
c. Yes

<!-- End solution -->

```{exercise, label="pill2cont", echo=TRUE}
**Amount of active substance**
    
  The amount of active substance in a pill is stated by the manufacturer to be normally distributed with mean 12 mg and standard deviation 0.5 mg.
  You take a sample of five pills and measure the amount of active substance to; 13.0, 12.3, 12.6, 12.5, 12.7 mg.
  
  [Note: a-c were already computed in the descriptive statistics session.]
  
  a) Compute the sample mean
  b) Compute the sample variance
  c) Compute the sample standard deviation
  d) compute the standard error of mean, $SEM$.
  e) If the manufacturers claim is correct, what is the probability to see a sample mean as high as in a) or higher?
```

*Solution*

*Answers*

a. 12.62
b. 0.067
c. 0.26
d. 0.22
e. 0.0028

a. Sample mean

```{r pill2cont, echo=TRUE}
x <- c(13.0, 12.3, 12.6, 12.5, 12.7)
n <- length(x)
(m <- sum(x)/n)
```

b. Sample variance

```{r}
(s2 <- sum((x-m)^2)/(n-1))
```

c. Sample standard deviation

```{r}
(s <- sqrt(s2))
```

d. Standard error of mean, SEM

```{r}
(SEM <- 0.5/sqrt(n))
```
Note, here the known standard deviation, $\sigma=0.5$ is used.


<!-- End solution -->
