project:
  type: book
  output-dir: docs
  
book:
  title: "Probability Theory"
  author: "Eva Freyhult"
  chapters:
    - index.qmd
    - prob_01intro.qmd
    - prob_02discrv.qmd
    - prob_exr1_discrv_solutions.qmd 
    - prob_03contrv.qmd
    - prob_04sample.qmd
    - prob_exr2_contrv_solutions.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

knitr:
  opts_chunk:
    fig.width: 3.5
    fig.height: 3.5
    echo: false
    error: false
    warnings: false
    dpi: 600
    fig.path: "docs/Rfigures/prob_"