# Preface {.unnumbered}

This repository contains teaching and learning materials prepared and used during "Introduction to biostatistics and machine learning" course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. More about the course <https://uppsala.instructure.com/courses/74597>

```{r include=FALSE}
## automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'quarto'
), 'packages.bib')
```

## Learning outcomes {.unnumbered}

-   understand the concept of random variables
-   understand the concept of probability
-   understand and learn to use resampling to compute probabilities
-   understand the concept probability mass function
-   understand the concept probability density function
-   understand the concept cumulative distribution functions
-   use normal distribution
-   understand the central limit theorem
