project:
  type: book
  output-dir: docs

book:
  title: "Supervised learning: foundations, evaluation and tuning"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - 01-overview.qmd
    - 02-knn.qmd
    - 03-svm.qmd
    - 04-generalization.qmd
    - 05-train-valid-test.qmd
    - 06-model-evaluation-cls.qmd
    - 07-model-evaluation-reg.qmd
    - 08-cv.qmd
    - 09-frameworks.qmd
    - 10-KNN-train-valid-test-demo.qmd
    - 11-exercise-KNN-cv.qmd
    - 12-demo-tidymodels.qmd
    - 13-demo-sklearn.qmd
    

format:
  html:
    theme: cosmo
    code-fold: true    
    
bibliography: references.bib






    
    


