project:
  type: book
  output-dir: ../docs/SM4LS
  
bibliography: references.bib

book:
  title: "Statistical Methods for Life Sciences"
  author: "Eva Freyhult, Olga Dethlefsen, Payam Emami"
  chapters:
    - index.qmd
    - part: "Probability Theory"
      chapters:
        - probability/prob_01intro.qmd
        - probability/prob_02discrv.qmd
        - probability/prob_exr1_discrv_solutions.qmd 
        - probability/prob_03contrv.qmd
        - probability/prob_04sample.qmd
        - probability/prob_exr2_contrv_solutions.qmd
        - probability/references.qmd
    - part: "Inference"
      chapters:
        - inference/infe_01hypothesis.qmd
        - inference/infe_02hypresamp.qmd
        - inference/infe_exr1_hyporesampling_solutions.qmd
        - inference/infe_03hypparm.qmd
        - inference/infe_04multiple.qmd
        - inference/infe_exr2_hypoparam_solutions.qmd
        - inference/infe_05interval.qmd
        - inference/infe_exr3_interval_solutions.qmd
    - part: "Linear Regression"
      chapters:
        - lm/index.qmd
        - lm/lm-intro.qmd
        - lm/lm-reg-cls.qmd
        - lm/lm-coeff.qmd
        - lm/lm-intro-exercises.qmd
        - lm/lm-diagn-exercises.qmd
        - lm/lm-lasso-exercises.qmd
        - lm/lm-coeff-exercises.qmd
    - part: "Principal Component Analysis"
      chapters:
        - pca/PCA.qmd
        - pca/exercises.qmd
    - part: "Clustering"
      chapters:
        - clustering/index.qmd
        - clustering/intro.qmd
        - clustering/exercises.qmd
    - part: "Generalized Linear Models"
      chapters:
        - glm/index.Rmd
        - glm/304-linear-GLM.Rmd
    - part: "Mixed Models"
      chapters:
        - mixedmodels/index.qmd
        - mixedmodels/environment.qmd
        - mixedmodels/lm.qmd
        - mixedmodels/lmm.qmd
        - mixedmodels/math.qmd
    - part: "Survival"
      chapters:
        - survival/index.qmd
        - survival/intro.qmd
        - survival/regression.qmd
        - survival/lab.qmd
        - survival/references.qmd



number-sections: true

format:
  html:
    theme: cosmo
    fig-width: 3.5
    fig-height: 3.5
    dpi: 600
    number-sections: true

editor: source

execute: 
  cache: true
  echo: false
  error: false
  warnings: false