project:
  type: book
  output-dir: ../docs/SM4LS
  
bibliography: references.bib

book:
  title: "Statistical Methods for Life Sciences"
  author: "Eva Freyhult, Olga Dethlefsen, Payam Emami"
  chapters:
    - index.qmd
    - part: probability/index.qmd #Probability Theory
      chapters:
        - probability/prob_01intro.qmd
        - probability/prob_02discrv.qmd
        - probability/prob_exr1_discrv_solutions.qmd 
        - probability/prob_03contrv.qmd
        - probability/prob_04sample.qmd
        - probability/prob_exr2_contrv_solutions.qmd
    - part: inference/index.qmd #Statistical Inference
      chapters:
        - inference/infe_01hypothesis.qmd
        - inference/infe_02hypresamp.qmd
        - inference/infe_exr1_hyporesampling_solutions.qmd
        - inference/infe_03hypparm.qmd
        - inference/infe_04multiple.qmd
        - inference/infe_exr2_hypoparam_solutions.qmd
        - inference/infe_05interval.qmd
        - inference/infe_exr3_interval_solutions.qmd
    - part: lm/index.qmd # Linear regression
      chapters:
        - lm/lm-intro.qmd
        - lm/lm-reg-cls.qmd
        - lm/lm-coeff.qmd
        - lm/lm-intro-exercises.qmd
        - lm/lm-diagn-exercises.qmd
        - lm/lm-lasso-exercises.qmd
        - lm/lm-coeff-exercises.qmd
    - part: pca/index.qmd # Principal Component Analysis
      chapters:
        - pca/PCA.qmd
        - pca/exercises.qmd
    - part: clustering/index.qmd #Clustering
      chapters:
        - clustering/intro.qmd
        - clustering/exercises.qmd
    - part: glm/index.qmd #"Generalized Linear Models"
      chapters:
        - glm/304-linear-GLM.Rmd
    - part: mixedmodels/index.qmd #"Mixed Models"
      chapters:
        - mixedmodels/lm.qmd
        - mixedmodels/lmm.qmd
        - mixedmodels/math.qmd
    - part: survival/index.qmd #"Survival"
      chapters:
        - survival/intro.qmd
        - survival/regression.qmd
        - survival/lab.qmd
    - references.qmd


number-sections: true

format:
  html:
    theme: cosmo
    fig-width: 3.5
    fig-height: 3.5
    dpi: 600
    number-sections: true

editor: source

execute: 
  cache: true
  echo: false
  error: false
  warnings: false