project:
  type: book
  output-dir: docs
    

book:
  title: "Descriptive statistics"
  author: "Eva Freyhult, Olga Dethlefsen"
  #date: "8/31/2022"
  chapters:
    - index.qmd
    - data-types.qmd
    - data-categorical.qmd
    - data-numerical.qmd
    - measures-of-location.qmd
    - measures-of-spread.qmd
    - exercises.qmd
    
# bibliography: references.bib

format:
  html:
    self-contained: false
    theme: cosmo
    code-fold: true
      
  pdf:
    documentclass: scrreprt



