# Data types

Depending on the data type we use different methods to describe, summarize and visualize the data. 
Especially, we differentiate between **categorical** (qualitative) and **numerical** (quantitative) data types. 


```{mermaid}
%%| label: fig-1
%%| fig-align: center
%%| fig-cap: "Main data types: categorical (qualitative) and numerical (quantitative)"
%%| fig-cap-location: margin

flowchart TD
  A(Data types) --> B(Categorical)
  A(Data types) --> C(Numerical)
  B --> D(Nominal)
  B --> E(Ordinal)
  C --> F(Discrete)
  C --> G(Continuous)
```

<br>
**Categorical data types are further divided into:**

- **Nominal**: named, categories are mutually exclusive and unordered
  - *e.g.dead/alive, healthy/sick, WT/mutant, blood group (A/B/ABO/O), male/female, red/green/blue*
- **Ordinal:** named and ordered, categories are mutually exclusive and ordered
  - *e.g. pain (weak, moderate, severe), AA/Aa/aa, very young/young/middle age/old/very old, grade I, II, III, IV*

**Numerical data types are further divided into:**

- **Discrete**: finite or countable infinite values
  - *e.g. days sick last year, number of cells, number of reads*
- **Continuous**: infinitely many uncountable values
  - *e.g. height, weight, concentration*
  
  
:::{.callout-tip}

## Good to remember

Depending on the data type we use different methods to describe, summarize and visualize the data. 
Beyond descriptive statistics, we even use different methods to analyse the data. 
:::
