# Preface {.unnumbered}

Descriptive statistics is a term describing simple analyses of data that help getting to know the data by describing the data, showing the data and summarizing the data. Descriptive statistics is used to guide down-stream data analysis and often helps to uncover patterns in the data.  


**Learning outcomes**

- understand why we are doing descriptive statistics
- understand the difference between data types and be able to select and use appropriate data summaries and plots for each data type
- compute measures of location, including mean and median
- compute measures of spread, including quantiles, variance and standard deviation
- compute population mean and variance
- compute sample mean and variance

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared and used during “Introduction to biostatistics and machine learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*


