{
  "hash": "3d225e6cf307e25e28b73a53629e49ff",
  "result": {
    "markdown": "# Exercises (introduction to linear models) {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n**Data for exercises** are on Canvas under Files -> data_exercises --> linear-models\n\n::: {#exr-protein}\n\n## Protein levels in pregnancy\n\nThe researchers were interested whether protein levels in expectant mothers are changing throughout the pregnancy. Observations have been taken on 19 healthy women and each woman was at different stage of pregnancy (gestation).\n\nAssuming linear model:\n\n- $Y_i = \\alpha + \\beta x_i + \\epsilon_i$, where $Y_i$ corresponds to protein levels in i-th observation\n\nand taking summary statistics:\n\n- $\\sum_{i=1}^{n}x_i = 456$\n- $\\sum_{i=1}^{n}x_i^2 = 12164$\n- $\\sum_{i=1}^{n}x_iy_i = 369.87$\n- $\\sum_{i=1}^{n}y_i = 14.25$\n- $\\sum_{i=1}^{n}y_i^2 = 11.55$\n\n\na) find the least square estimates of $\\hat{\\alpha}$ and $\\hat{\\beta}$\nb) knowing that e.s.e($\\hat{\\beta}) = 0.003295$\n\ncan we:\n\n- i) reject the null hypothesis that the is no relationship between protein level and gestation, i.e. perform a hypothesis test to test $H_0:\\beta = 0$;\n- ii) can we reject the null hypothesis that $\\beta = 0.02$, i.e.  perform a hypothesis test to test $H_0:\\beta = 0.02$\nc) write down the linear model in the vector-matrix notation and identify response, parameter, design and error matrices\nd) read in \"protein.csv\" data into R, set Y as protein (response) and calculate using matrix functions the least squares estimates of model coefficients\ne) use `lm()` function in R to check your calculations\nf) use the fitted model in R to predict the value of protein levels at week 20. Try plotting the data, fitted linear model and the predicted value to assess whether your prediction is to be expected.\n\n:::\n\n\n::: {#exr-potato}\n\n## Glucose levels in potatoes\n\nThe glucose level in potatoes depends on their storage time and the relationship is somehow curvilinear as shown below.\nAs we believe that the quadratic function might describe the relationship, assume linear model in form\n$Y_i = \\alpha + \\beta x_i + \\gamma x_i^2 + \\epsilon_i \\quad i=1,\\dots,n$ where $n=14$ and\n\na) write down the model in vector-matrix notation\nb) load data from \"potatoes.csv\" and use least squares estimates to obtain estimates of model coefficients\nc) use `lm()` function to verify your calculations\nd) perform a hypothesis test to test $H_0:\\gamma=0$; and comment whether there is a significant quadratic relationship\ne) predict glucose concentration at storage time 4 and 16 weeks. Plot the data, the fitted model and the predicted values\n\n:::\n\n\n\n\n::: {.cell fig.heigth='5'}\n\n```{.r .cell-code}\ndata.potatoes <- read.csv(\"data/lm/potatoes.csv\")\nplot(data.potatoes$Weeks, data.potatoes$Glucose, pch=19, xlab=\"Storage time [weeks]\", ylab=\"Glucose [g/kg]\")\n```\n\n::: {.cell-output-display}\n![Sugar in potatoes: relationship between storage time and glucose content](lm-intro-exercises_files/figure-pdf/fig-potatoes-1.pdf){#fig-potatoes fig-pos='H'}\n:::\n:::\n\n\n\n::: {#exr-recognize}\n\n## Linear models form\n\nWhich of the following models are linear models and why?\n\na) $Y_i=\\alpha + \\beta x_i + \\epsilon_i$\nb) $Y_i=\\beta_0 + \\beta_1 x_{i,1} + \\beta_2 x_{i,2} + \\epsilon_i$\nc) $Y_i=\\alpha + \\beta x_i + \\gamma x_i^2 + \\epsilon_i$\nd) $Y_i=\\alpha + \\gamma x_i^\\beta + \\epsilon_i$\n\n::: \n\n------------\n\n\n\n## Answers to selected exercises \n\n::: {.solution}\n\n@exr-protein\n\n::: \n\na)\n\n- $S_{xx} = \\sum_{i=1}^{n}x_i^2-\\frac{(\\sum_{i=1}^{n}x_i)^2}{n} = 12164 - \\frac{456^2}{19} = 1220$\n- $S_{xy} = \\sum_{i=1}^nx_iy_i-\\frac{\\sum_{i=1}^{n}x_i\\sum_{i=1}^{n}y_i}{n} = 369.87 - \\frac{(456 \\cdot 14.25)}{19} = 27.87$\n- $\\hat{\\beta} = \\frac{S_{xy}}{S_{xx}} = 27.87 / 1220 = 0.02284$\n- $\\hat{\\alpha} = \\bar{y}-\\frac{S_{xy}}{S_{xx}}\\cdot \\bar{x} = \\frac{14.25}{19}-\\frac{27.87}{1220}\\cdot \\frac{456}{19} = 0.20174$\n\nb) i.\n\nWe can calculate test statistics following:\n\n- $\\frac{\\hat{\\beta} - \\beta}{e.s.e(\\hat{\\beta})} \\sim t(n-p) = \\frac{0.02284 - 0}{0.003295} = 6.934$ where the value follows Student's t distribution with $n-p = 19 - 2 = 17$ degrees of freedom. We can now estimate the a p-value using Student’s t distribution table or use R function\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n2*pt(6.934, df=17, lower=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.414315e-06\n```\n:::\n:::\n\n\nAs p-value << 0.001 there is sufficient evidence to reject $H_0$ in favor of $H_1$, thus we can conclude that there is a significant relationship between protein levels and gestation\n\nb) ii.\n\nSimilarly, we can test $H_0:\\beta = 0.02$, i.e. $\\frac{\\hat{\\beta} - \\beta}{e.s.e(\\hat{\\beta})} \\sim t(n-p) = \\frac{0.02284 - 0.02}{0.20174} = 0.01407753$. Now the test statistics is small\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n2*pt(0.01407753, df=17, lower=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.988932\n```\n:::\n:::\n\n\np-value is large and hence there is no sufficient evidence to reject $H_0$ and we can conclude that $\\beta = 0.02$\n\nc) We can rewrite the linear model in vector-matrix formation as $\\mathbf{Y}= \\mathbf{\\beta}\\mathbf{X} + \\mathbf{\\epsilon}$ where:\n\nresponse $\\mathbf{Y}=\\begin{bmatrix}\n  y_1  \\\\\n  y_2    \\\\\n  \\vdots \\\\\n  y_{19}\n\\end{bmatrix}$\n\nparameters $\\boldsymbol\\beta=\\begin{bmatrix}\n  \\alpha \\\\\n  \\beta\n\\end{bmatrix}$\n\ndesign matrix $\\mathbf{X}=\\begin{bmatrix}\n  1 & x_1  \\\\\n  1 & x_2  \\\\\n  \\vdots & \\vdots \\\\\n  1 & x_{19}\n\\end{bmatrix}$\n\nerrors $\\boldsymbol\\epsilon=\\begin{bmatrix}\n  \\epsilon_1  \\\\\n  \\epsilon_2    \\\\\n  \\vdots \\\\\n  \\epsilon_{19}\n\\end{bmatrix}$\n\nd) The least squares estimates in vector-matrix notation is $\\hat{\\boldsymbol\\beta}= (\\mathbf{X}^T\\mathbf{X})^{-1}\\mathbf{X}^T\\mathbf{Y}$ and we can calculate this in R\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# read in data\ndata.protein <- read.csv(\"data/lm/protein.csv\")\n\n# print out top observations\nhead(data.protein)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Protein Gestation\n1    0.38        11\n2    0.58        12\n3    0.51        13\n4    0.38        15\n5    0.58        17\n6    0.67        18\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# define Y and X matrices given the data\nn <- nrow(data.protein) # nu. of observations\nY <-  as.matrix(data.protein$Protein, ncol=1) # response\nX <-  as.matrix(cbind(rep(1, length=n), data.protein$Gestation)) # design matrix\nhead(X) # double check that the design matrix looks like it should\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2]\n[1,]    1   11\n[2,]    1   12\n[3,]    1   13\n[4,]    1   15\n[5,]    1   17\n[6,]    1   18\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# least squares estimate\nbeta.hat <- solve(t(X)%*%X)%*%t(X)%*%Y # beta.hat is a matrix that contains our alpha and beta in the model\nprint(beta.hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           [,1]\n[1,] 0.20173770\n[2,] 0.02284426\n```\n:::\n:::\n\n\n\ne) We use `lm()` function to check our calculations\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# fit linear regression model and print model summary\nprotein <- data.protein$Protein # our Y\ngestation <- data.protein$Gestation # our X\n\nmodel <- lm(protein ~ gestation)\nprint(summary(model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = protein ~ gestation)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.16853 -0.08720 -0.01009  0.08578  0.20422 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.201738   0.083363   2.420    0.027 *  \ngestation   0.022844   0.003295   6.934 2.42e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1151 on 17 degrees of freedom\nMultiple R-squared:  0.7388,\tAdjusted R-squared:  0.7234 \nF-statistic: 48.08 on 1 and 17 DF,  p-value: 2.416e-06\n```\n:::\n:::\n\n\n\nf)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nnew.obs <- data.frame(gestation = 20)\ny.pred <- predict(model, newdata = new.obs)\n\n# we can visualize the data, fitted linear model (red), and the predicted value (blue)\nplot(gestation, protein, pch=19, xlab=\"gestation [weeks]\", ylab=\"protein levels [mgml-1]\")\nlines(gestation, model$fitted.values, col=\"red\")\npoints(new.obs, y.pred, col=\"blue\", pch=19, cex = 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro-exercises_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n::: {.solution}\n\n@exr-potato\n\n:::\n\n\na) We can rewrite the linear model in vector-matrix formation as $$\\mathbf{Y} = \\mathbf{X}\\boldsymbol\\beta + \\boldsymbol\\epsilon$$\n\nwhere:\nresponse $\\mathbf{Y}=\\begin{bmatrix}\n  y_1  \\\\\n  y_2    \\\\\n  \\vdots \\\\\n  y_{14}\n\\end{bmatrix}$\n\nparameters $\\boldsymbol\\beta=\\begin{bmatrix}\n  \\alpha \\\\\n  \\beta \\\\\n  \\gamma\n\\end{bmatrix}$\n\ndesign matrix $\\mathbf{X}=\\begin{bmatrix}\n  1 & x_1  & x_1^2\\\\\n  1 & x_2  & x_2^2\\\\\n  \\vdots & \\vdots & \\vdots \\\\\n  1 & x_{14} & x_{14}^2\n\\end{bmatrix}$\n\nerrors $\\boldsymbol\\epsilon=\\begin{bmatrix}\n  \\epsilon_1  \\\\\n  \\epsilon_2    \\\\\n  \\vdots \\\\\n  \\epsilon_{14}\n\\end{bmatrix}$\n\n\nb) load data to from \"potatoes.csv\" and use least squares estimates for obtain estimates of model coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndata.potatoes <- read.csv(\"data/lm/potatoes.csv\")\n\n# define matrices\nn <- nrow(data.potatoes)\nY <-  data.potatoes$Glucose\nX1 <- data.potatoes$Weeks\nX2 <- (data.potatoes$Weeks)^2\nX <- cbind(rep(1, length(n)), X1, X2)\nX <- as.matrix(X)\n\n# least squares estimate\n# beta here refers to the matrix of model coefficients incl. alpha, beta and gamma\nbeta.hat <- solve(t(X)%*%X)%*%t(X)%*%Y\nprint(beta.hat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         [,1]\n   200.169312\nX1 -19.443122\nX2   1.030423\n```\n:::\n:::\n\n\n\nc) we use `lm()` function to verify our calculations:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel <- lm(Y ~ X1 + X2)\nprint(summary(model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Y ~ X1 + X2)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-17.405 -11.250  -8.071  12.911  29.286 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 200.1693    15.0527  13.298 4.02e-08 ***\nX1          -19.4431     3.1780  -6.118 7.54e-05 ***\nX2            1.0304     0.1406   7.329 1.49e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.4 on 11 degrees of freedom\nMultiple R-squared:  0.8694,\tAdjusted R-squared:  0.8457 \nF-statistic: 36.61 on 2 and 11 DF,  p-value: 1.373e-05\n```\n:::\n:::\n\n\n\nd) perform a hypothesis test to test $H_0:\\gamma=0$; and comment whether we there is a significant quadratic term\n- $\\frac{\\hat{\\gamma} - \\gamma}{e.s.e(\\hat{\\gamma})} \\sim t(n-p) = \\frac{1.030423 - 0}{0.1406} = 7.328755$ where the value follows Student's t distribution with $n-p = 19 - 2 = 17$ degrees of freedom. We can now estimate the a p-value using Student’s t distribution table or use a function in R\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n2*pt(7.328755, df=14-3, lower=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.487682e-05\n```\n:::\n:::\n\n\nAs p-value << 0.001 there is sufficient evidence to reject $H_0$ in favor of $H_1$, thus we can conclude that there is a significant quadratic relationship between glucose and storage time\n\ne) predict glucose concentration at storage time 4 and 16 weeks\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nnew.obs <- data.frame(X1 = c(4, 16), X2 = c(4^2, 16^2))\npred.y <- predict(model, newdata = new.obs)\n\nplot(data.potatoes$Weeks, data.potatoes$Glucose, xlab=\"Storage time [weeks]\", ylab=\"Glucose [g/kg]\", pch=19)\nlines(data.potatoes$Weeks, model$fitted.values, col=\"red\")\npoints(new.obs[,1], pred.y, pch=19, col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](lm-intro-exercises_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n",
    "supporting": [
      "lm-intro-exercises_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}