---
title: "knn-demo"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}

# load libraries
library(tidyverse)
library(splitTools)
library(kknn)
library(faraway)

# input data
#input_diabetes <- read_csv("data/data-diabetes.csv")
input_diabets <- diabetes

# clean data
inch2cm <- 2.54
pound2kg <- 0.45
data_diabetes <- input_diabetes %>%
  mutate(height  = height * inch2cm / 100, height = round(height, 2)) %>% 
  mutate(waist = waist * inch2cm) %>% 
  mutate(weight = weight * pound2kg, weight = round(weight, 2)) %>%
  mutate(BMI = weight / height^2, BMI = round(BMI, 2)) %>%
  mutate(obese= cut(BMI, breaks = c(0, 29.9, 100), labels = c("No", "Yes"))) %>%
  mutate(diabetic = ifelse(glyhb > 7, "Yes", "No"), diabetic = factor(diabetic, levels = c("No", "Yes"))) %>%
  mutate(location = factor(location)) %>%
  mutate(frame = factor(frame)) %>%
  mutate(gender = factor(gender))
  
```


```{r}
# select data for KNN
data_input <- data_diabetes %>%
  select(obese, waist, hdl) %>%
  na.omit()

# preview data
glimpse(data_input)

# How many obese and non-obese in our data set?
data_input %>%
  count(obese)

# make a plot
data_input %>%
  ggplot(aes(x = waist, y = hdl, fill = obese)) + 
  geom_point(shape=21, alpha = 0.7, size = 2) + 
  theme_bw() + 
  scale_fill_manual(values = c("blue3", "brown1")) + 
  theme(legend.position = "top")

```


```{r}
# split data into train (40%), validation (40%) and test (20%)
# stratify by obese
randseed <- 123
set.seed(randseed)

inds <- partition(data_input$obese, p = c(train = 0.4, valid = 0.4, test = 0.2), seed = randseed)
str(inds)

data_train <- data_input[inds$train,]
data_valid <- data_input[inds$valid,]
data_test <- data_input[inds$test, ]

# check dimensions of data
data_train %>% dim()
data_valid %>% dim()
data_test %>% dim()

# check distribution of obese and non-obese
data_train %>%
  group_by(obese) %>%
  count()

data_valid %>%
  group_by(obese) %>%
  count()

data_test %>%
  group_by(obese) %>%
  count()

```


```{r}
# prepare parameters search space
n <- nrow(data_train)
k_values <- seq(1, n-1, 2) # check every odd value of k between 1 and number of samples-1

# allocate empty vector to collect overall classification rate for each k
cls_rate <- rep(0, length(k_values)) 

for (l in seq_along(k_values))
{
  
  # fit model given k value
  model <- kknn(obese ~., data_train, data_valid, 
                k = k_values[l], 
                kernel = "rectangular")
  
  # extract predicted class (predicted obesity status)
  cls_pred <- model$fitted.values
  
  # define actual class (actual obesity status)
  cls_true <- data_valid$obese
  
  # calculate overall classification rate
  cls_rate[l] <- sum((cls_pred == cls_true))/length(cls_pred)
  
}
```


```{r}
# plot classification rate as a function of k
plot(k_values, cls_rate, type="l", xlab="k", ylab="cls rate")
```


```{r}

k_best <- 22


# How would our model perform on the future data using the optimal k?
model_final <- kknn(obese ~., data_train, data_test, k=k_best, kernel = "rectangular")
cls_pred <- model_final$fitted.values
cls_true <- data_test$obese

cls_rate <- sum((cls_pred == cls_true))/length(cls_pred)
print(cls_rate)

```



