---
title: "R, RStudio and R Markdown"
output:
  bookdown::gitbook:
    keep_md: false
    number_sections: true
---

# Preface {-}

During the course we will be using `R` programming language within `RStudio Desktop` editor. We will be writing scripts using `R Markdown` (.Rmd). We will try to keep coding as simple as possible, but we do assume that you have a basic understanding of R and your computer setup with RStudio and R version 3.5.0 or higher.  

R skills that will be useful during the course are: 

- using R as calculator incl. raising values to a power
- being able to work with vectors and matrices, incl. subsetting and matrices multiplication 
- reading in data from .csv files, e.g. with `read.delim()`
- printing top few rows or last few rows, e.g. with `head()` and `tail()`
- using in-built summary functions such as `sum()`, `min()` or `max()`
- being able to use documentation pages for R functions, e.g. with `help()` or `?()`
- using if else statements, writing simple loops and functions.
- making simple scatter plots of one numerical variable against another, both with `plot()` and `ggplot()`
- being able to install CRAN packages e.g. with `install.packages()`
- being familiar with R Markdown format

```{r, child="01-install.Rmd"}
```


