project:
  type: book
  output-dir: docs

book:
  title: "session-rank-tests"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - wilcoxon-signed-rank-i.qmd
    - wilcoxon-signed-rank-ii.qmd
    - wilcoxon-rank-sum.qmd
    - kruskal-wallis.qmd
    - correlation.qmd
    - exercises.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt



