# Preface {.unnumbered}

Hypothesis tests that are based on knowledge of the probability distributions (e.g. normal or binomial) that the data follow are known as **parametric tests**. When data do not meet the parametric test assumptions, we can use **non-parametric** tests, also called distribution free tests, that replace the data with their ranks. 

**Learning outcomes**

- know when to use non-parametric tests, their advantages and limitations
- name the main rank methods and their parametric counterparts
- explain how Wilcoxon signed rank test and Wilcoxon rank sum test work in detail
- be able to use R to compute Wilcoxon signed rank test, Wilcoxon rank sum test and Kruskal-Wallis one way analysis of variance

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared and used during “Introduction to biostatistics and machine learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*

