---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Introduction

Hypothesis tests that are based on knowledge of the probability distributions (e.g. normal or binomial) that the data follow are known as **parametric tests**. When data do not meet the parametric test assumptions, we can use **non-parametric** tests, also called distribution free tests, that replace the data with their ranks. These tests came before computers enabled resampling to obtain the null distribution as seen before and are still being used in hypothesis testing.

## Pros and cons 

**Pros**

Non-parametric rank based test are useful when:

- we do not know the underlying probability distribution and/or our data does not meet parametric test requirements
- sample size is too small to properly assess the distribution of the data
- transforming our data to meet the parametric test requirements would make interpretation of the results harder

**Cons**

Some limitations of the non-parametric rank based tests include the facts that:

- they are primary significance tests that often do not provide estimates of the effects of interest
- they lead to waste of information and in consequence they have less power
- when sample size are extremely small (e.g. $n=3$) rank tests cannot produce small P-values, even when the outcomes in the two groups are very different
- non-parametric tests are less easily extended to situations where we wish to take into account the effect of more than one exposure on the outcome

## Main non-parametric rank tests

- **Wilcoxon signed rank test**
  - compares the sample median against a hypothetical median (equivalent to one sample *t*-test)
  - or examine the difference between paired observations (equivalent to paired *t*-test)
- **Wilcoxon rank sum test**
  - examines the difference between two unrelated groups
  - equivalent to two sample *t*-test
- **Kruskal-Wallis one-way analysis of variance**
  - examines the difference between two or more  unrelated groups
  - equivalent to ANOVA
- **Spearman's rank correlation**
  - assess correlation on ranks
  - alternative to Pearson correlation coefficient
- **Kendall's rank correlation**
  - assess correlation on ranks
  - alternative to Pearson correlation coefficient


