project:
  type: book
  output-dir: docs

book:
  title: "Clustering"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - exercises.qmd
    #- references.qmd
    
bibliography: ref.bib


format:
  html:
    theme: spacebar
    code-fold: true
    toc-depth: 4
    # mermaid:
    #   theme: forest

    
    


