# Preface {.unnumbered}

**Aims**

- to introduce cluster analysis with focus on partitioning and hierarchical methods

**Learning outcomes**

- to be able to explain what clustering is
- to be able to run k-means, PAM and HCL cluster analysis
- to be able to evaluate cluster solutions

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared for and used during “Introduction to biostatistics and Machine Learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use the basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*





