project:
  type: book
  output-dir: docs

book:
  title: "Probability"
  author: "Olga Dethlefsen, Eva Freyhult"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - 01-why-do-we-care-about-pr.qmd
    - 02-describing-uncertain-obs.qmd
    - 03-describing-outcomes-with-pr-models.qmd
    - 04-repeat-the-sampling.qmd
    - 05-describing-precision.qmd
    - 06-exercises.qmd
    - prob_02discrv.qmd
    - prob_03contrv.qmd
    # - references.qmd
    
# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true




