project:
  type: book
  output-dir: docs

book:
  title: "From Linear Models to Machine Learning"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - from-inference-to-prediction.qmd
    - regularization.qmd
    - exr-lasso.qmd
    #- lm-intro.qmd
   # - lm-glm.qmd
   # - lm-coeff.qmd
    #- lm-reg-cls.qmd
    #- lm-intro-exercises.qmd
    #- lm-diagn-exercises.qmd
    #- lm-coeff-exercises.qmd
    #- lm-lasso-exercises.qmd

    # - references.qmd
    
# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true




