project:
  type: book
  output-dir: docs
    

book:
  title: "Neutral Networks"
  author: "Olga Dethlefsen"
  #date: "8/31/2022"
  chapters:
    - index.qmd
    - lab-R.qmd

bibliography: references.bib

format:
  html:
    self-contained: false
    theme: cosmo
    code-fold: true
      
  # pdf:
  #   documentclass: scrreprt



