project:
  type: book
  output-dir: docs

book:
  title: "Survival Analysis"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - regression.qmd
    - lab.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: spacebar
    code-fold: true
    mermaid:
      theme: forest

    
    


