project:
  type: book
  output-dir: docs

book:
  title: "Tidymodels"
  author: "Olga Dethlefsen"
  # date: "8/31/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - case-study.qmd
    - exercises.qmd
    
bibliography: references.bib

format:
  html:
    theme: spacebar
    code-fold: true
    mermaid:
      theme: forest

    
    


