# Preface {.unnumbered}

**Aims**

- to introduce `tidymodels` framework for predictive modelling studies
- and show how to put all the common steps for building predictive model

**Learning outcomes**

- to be able to use `tidymodels` framework for a complete workflow of supervised learning

Do you see a mistake or a typo? We would be grateful if you let us know via [edu.ml-biostats@nbis.se](edu.ml-biostats@nbis.se)

*This repository contains teaching and learning materials prepared for and used during “Introduction to biostatistics and Machine Learning” course, organized by NBIS, National Bioinformatics Infrastructure Sweden. The course is open for PhD students, postdoctoral researcher and other employees within Swedish universities. The materials are geared towards life scientists wanting to be able to understand and use the basic statistical and machine learning methods. More about the course [https://nbisweden.github.io/workshop-mlbiostatistics/](https://nbisweden.github.io/workshop-mlbiostatistics/)
*





